### ISSUE TITLE
Duplicated block is placed at the upper left corner of the initial block, instead of at the mouse location.

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#1006]
### Expected Behavior

Duplicated blocks that attach to the mouse pointer should have the mouse pointer placed correctly relative to the upper left corner of the block.

### Actual Behavior

The block is positioned according to the upper left corner of the block that was duplicated, and then there's a jump the first time the mouse moves.

(After #1001 lands)

### Steps to Reproduce

Create a block
Right click the block in the lower right corner.
Select "Duplicate"
Move the mouse.

### Operating System and Browser

All

**Comment by towerofnix** [comment]
I'm quite confident the solution to this is to finish up this: https://github.com/rachel-fenichel/scratch-blocks/blob/d7c33b5ec10755ed9c93ba226976cb3effc15559/core/block_svg.js#L696-L697

Doing that means somehow knowing the position of the mouse before a mousemove event happens, and appropriately offsetting the block position. The problem is exactly how to know the mouse position. I don't see anything on the `action` event that would be useful (which makes sense, e.g. if the duplicate button was somehow activated by the keyboard instead of the mouse). Is there any variable that constantly keeps track of the mouse position on the workspace, maybe? (But I doubt it.)

**Comment by rachel-fenichel** [comment]
Yes, that's the correct place to add code to fix this.

No, there's no code that tracks the mouse position continuously.  And the event that comes from the click on the context menu is not quite a mouse event, and is missing the information we would need.

**Comment by epicfaace** [comment]
@rachel-fenichel What's wrong with using the event from the click on the context menu? I implemented using that in the PR above and the duplicate behavior seems to be working smoothly now.

**Comment by rachel-fenichel** [comment]
@epicfaace I think it still will be a little bit off if there's a big difference between mouse position when opening the context menu and mouse position when clicking on the context menu item (like if you click all the way on the right side of the "duplicate" option).  

That said, I think your solution will almost always feel better than what's currently implemented, and reduces the mismatch between mouse position and block position significantly, so I think you should go for it.

**Comment by epicfaace** [comment]
@rachel-fenichel Yeah, that's also the same behavior in Scratch 2.0, so I'd think it's good. Unless we want to change that behavior?
