### ISSUE TITLE
How can I build a new block?

### ISSUE THREAD

**Issue by zyctinker** [LLK/scratch-blocks#1008]
### Question:How can I build a new block?
Hi everyone,
I'm trying to build a new block for scratch block to get message from serial port. But it seems that scratch-block doesn't translate block to programming language codes as other programs built in blockly usually do. So How can I add some JavaScript codes to a block? Or Are there any other way for scratch-block to translate block to programming language code?
Sry for my poor English because English is my second language. Thanks for your help.

**Comment by ericrosenbaum** [comment]
The Scratch Team uses Scratch-Blocks with the [Scratch Virtual Machine](https://github.com/llk/scratch-vm), which executes the blocks. This is because the VM lets people tinker with code: click on a block to run it, see a stack of blocks highlight while it's running, modify a stack while it's running, run several stacks in parallel, etc. 

Sorry we don't have better documentation for the Scratch VM- we plan to create it.

Technically, it is possible to use code generators with Scratch-Blocks, but the best documentation is what you have probably already seen on Blockly [here](https://developers.google.com/blockly/guides/configure/web/code-generators).
