### ISSUE TITLE
Empty space appears at bottom of page when context menu is visible

### ISSUE THREAD

**Issue by TheInitializer** [LLK/scratch-blocks#1017]
### Expected Behavior

When right-clicking to bring up the context menu, nothing should happen to the rest of the page.

### Actual Behavior

A large blank space appears below the editor, causing a scrollbar to appear.

### Steps to Reproduce

Right-click in the scripts pane.

### Operating System and Browser

Windows 10, Firefox Nightly 56

**Comment by Kenny2github** [comment]
May I refer you to [#548](https://github.com/LLK/scratch-gui/issues/548)

**Comment by rschamp** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/548

**Comment by rachel-fenichel** [comment]
Why is it being tracked in scratch-gui?  I'm pretty sure this is a scratch-blocks bug, and possibly just a blockly bug.  Does right-clicking anywhere other than the workspace cause the same problem?

**Comment by TheInitializer** [comment]
@rachel-fenichel I tried right clicking in other places, and the bug didn't seem to appear, so it seems like it's just in the workspace.

Is the context menu not part of scratch-blocks? It seemed specific to the blocks to me. I could be wrong though.

**Comment by rschamp** [comment]
@rachel-fenichel Because that issue was filed already, contains more information, and we haven't investigated to know whether it's actually in scratch-blocks or in the scratch-gui css. When it gets investigated and turns out to be due to scratch-blocks itself, then we can move it, but I wanted to keep that bug as the single place for conversation about it since it already exists.

If you're sure it's in scratch-blocks itself, then I'll move that issue over here.

**Comment by rachel-fenichel** [comment]
I'm 90% certain it's a scratch-blocks or blockly issue, but don't currently have time to investigate, so I'm fine with you leaving it in scratch-gui.
