### ISSUE TITLE
Text and input fields are offset on Edge & IE11

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-blocks#1054]
### Expected Behavior

Text and input fields on blocks should look the same across browsers.

### Actual Behavior

On Windows Edge, text on the blocks is slightly offset. This looks like several closely related text layout bugs:

- Text in labels and input fields is slightly too high
- On some blocks (such as 'move') the first label starts too far to the left
- On other blocks (such as 'point in direction') the first label starts too far to the right
- In some cases there is extra space between labels and other fields

![screenshot_2017-08-24_16-36-49](https://user-images.githubusercontent.com/567844/29690030-4f27874c-88f3-11e7-9f27-7e69c3ad74a5.png)

- While a block is being dragged, the input field is offset. ~~the offset seems to vary by block~~ actually the offset is controlled by the initial speed of the drag! if you click on the block and drag quickly away from the palette, the offset is larger.

Slow drag:
![screenshot_2017-09-07_15-03-29](https://user-images.githubusercontent.com/567844/30180776-0e1f1232-93df-11e7-9da4-9b238b4534d0.png)

Medium speed drag:
![screenshot_2017-09-07_15-04-48](https://user-images.githubusercontent.com/567844/30180788-16a57180-93df-11e7-9b39-34a52073230e.png)

Fast drag:
![screenshot_2017-09-07_15-05-59](https://user-images.githubusercontent.com/567844/30180791-1bba18c4-93df-11e7-909b-827dc1cece55.png)

We saw very similar issues in IE11 but I don't have screenshots.

This seems similar to but not necessarily the same as https://github.com/LLK/scratch-blocks/issues/820 

### Operating System and Browser

Microsoft Edge 40.15063.0.0
Windows 10 Enterprise Evaluation Version 1703 

Internet Explorer 11.0.9600.17416
Windows 8.1

**Comment by tmickel** [comment]
partially my fault, although I actually blame it on IE/Edge :)

Their SVG implementation doesn't support `dominant-baseline` (vertical positioning) or `text-anchor` (horizontal positioning) (last I checked). Luckily this is pretty easily fixed - you can calculate where the text is supposed to be in JS and strip out those properties. I had a branch for this a long time ago, but have since lost it.

**Comment by samelhusseini** [comment]
As @tmickel mentioned the positioning of the text being off is due to the use of text-anchor and dominant-baseline, which aren't supported on <= Edge 14. Although it is supported on IE 11..

The other issue you see here is the mid-drag rendering issue. The reason you're seeing this is because Blockly does re-renders only for Edge and IE to get around an issue with getComputedTextLength. (outlined in field.js::getCachedWidth)
This ends up calling renders mid-drag, and hence you see fields rendered in the wrong spots as you drag a block.
I've been working on a solution that avoids the need for a re-render on IE and Edge, see Blockly PR: https://github.com/google/blockly/pull/1326
Thought I'd reference that here, in case you someone was looking into this issue. Stay tuned.

**Comment by paulkaplan** [comment]
Looks like Edge 16 still doesn't support dominant baseline...

![image](https://user-images.githubusercontent.com/654102/34792267-6defa7c4-f615-11e7-89e7-d5922c0bb721.png)

To be fair to edge, baselines are hard. All major browsers seem to choose random values...
![image](https://user-images.githubusercontent.com/654102/34792289-891c9408-f615-11e7-94b6-4affc49f5e8f.png)
http://bl.ocks.org/eweitnauer/7325338
