### ISSUE TITLE
"Duplicate" option on mobile doesn't work as expected

### ISSUE THREAD

**Issue by msintov** [LLK/scratch-blocks#1065]
### Expected Behavior

On mobile, the "Duplicate" option on a block should result in the block being duplicated and draggable in an intuitive way.

### Actual Behavior

After clicking "Duplicate", a shadow in the shape of a block appears above the workspace but it's not obvious was gesture the user should do next. Clicking certain areas of the screen result in the new block being drawn (like clicking on the block being copied), but clicking in other areas of the workspace does nothing, the zoom controls don't respond, and the scrollbars don't work.

### Steps to Reproduce

1. Open tests/vertical_playground.html in Chrome
2. From the Chrome menu, select View -> Developer -> Developer tools
3. Drag any block to the workspace (e.g., "move 10 steps")
4. Long-press the block on the workspace
5. Select "Duplicate"

### Operating System and Browser

Mac OS 10.11.6 Chrome 59

**Comment by Kenny2github** [comment]
Furthermore, on laptops with touchscreens:
1. Press and hold a block in the workspace.
2. Select "Duplicate".
3. Tap anywhere on the screen - the block will go there but *will not be placed* - only a mouse click will place it, *not* a touchscreen tap.
OS&B:
Raspbian Pixel Desktop Chrome 57

**Comment by rachel-fenichel** [comment]
Laptops with touchscreens and mobile devices are treated the same.

It looks like I missed adding an event listener for touch events when faking a gesture start for duplication.  That's not that surprising, since sticking to the mouse pointer on duplicate breaks the idea that a drag always starts with a mouse down/touch start on a block.

Here's the function that forces a drag to start: https://github.com/LLK/scratch-blocks/blob/develop/core/gesture.js#L804
Notice that the event isn't a real event, because we don't have access to an actual mouse/touch event through the right-click menu.  There's probably something missing on the event that needs to be faked.

This will be spectacularly broken on Edge with a touchscreen, but so is everything else touch-related right now.

**Comment by rachel-fenichel** [comment]
Actually, per https://github.com/LLK/scratch-blocks/issues/828, it looks like the plan was to not have a context menu on touch screens.  @thisandagain is that still the plan?

**Comment by rachel-fenichel** [comment]
Fixed by #1742
