### ISSUE TITLE
Update category menu selection when dragging flyout or scrollbar 

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-blocks#1070]
### Expected Behavior

In the auto-scrolling flyout with all the blocks ([PR](https://github.com/LLK/scratch-blocks/pull/1059)), the selected category should update when you scroll the flyout in any way. 

### Actual Behavior

Currently, the category selection is only updated on a "wheel" scroll event (via mouse wheel or trackpad scrolling gesture). It does not update when you scroll it by dragging the flyout or dragging the scrollbar.

### Operating System and Browser

Mac OS 10.11.6 Chrome 60.0

**Comment by ericrosenbaum** [comment]
Any pointers on this one @picklesrus or @rachel-fenichel?

**Comment by rachel-fenichel** [comment]
Flyout's `setMetrics` is called when it's being scrolled ([vertical](https://github.com/LLK/scratch-blocks/blob/develop/core/flyout_vertical.js#L228) and [horizontal](https://github.com/LLK/scratch-blocks/blob/develop/core/flyout_horizontal.js#L123)).

That's because scrollbar's `set` calls `onScroll_`, which calls `setMetrics` on the relevant workspace:

```

/**
 * Called when scrollbar is moved.
 * @private
 */
Blockly.Scrollbar.prototype.onScroll_ = function() {
  var ratio = this.handlePosition_ / this.scrollViewSize_;
  if (isNaN(ratio)) {
    ratio = 0;
  }
  var xyRatio = {};
  if (this.horizontal_) {
    xyRatio.x = ratio;
  } else {
    xyRatio.y = ratio;
  }
  this.workspace_.setMetrics(xyRatio);
};

/**
 * Set the scrollbar slider's position.
 * @param {number} value The distance from the top/left end of the bar.
 */
Blockly.Scrollbar.prototype.set = function(value) {
  this.setHandlePosition(this.constrainHandle_(value * this.ratio_));
  this.onScroll_();
};
```

`wheel_` also calls `scrollbar.set()`, so you'll want to remove that code from `wheel_` and only have it in `setMetrics`.  Beware of accidentally setting up loops between scrolling and setMetrics.  That could happen if setting the selected category on the toolbox makes it scroll the flyout to that category, for instance.
