### ISSUE TITLE
Incorrect "change" event when renaming variables

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-blocks#1183]
In the vertical playground, create a variable and drag the new "set <x> to <y>" block into the workspace. Open the dropdown and rename the variable to something else. 

There are two events, a `VarRename` and a `Change` for the variable field. The `VarRename` seems ok, it has the varId, oldName and newName. The `Change` event, though, doesn't look it has the right fields: the `oldValue` is the variable ID and the `newValue` is the new variable name. It looks like a confusion between the field value and the field name w/r/t variables, which is something that was changed to separate variable Ids and names. 

I believe this is the root cause of https://github.com/LLK/scratch-vm/issues/723

The change event is a problem because it is identical to the change event you get when changing to a different variable in the dropdown. In that case, `oldValue` and `newValue` are both variable IDs, so everything works.

**Comment by paulkaplan** [comment]
I can also replicate this in the google/blockly develop playground

**Comment by paulkaplan** [comment]
It looks like it would be possible to patch this behavior in the VM by checking if there is a variable with  `id=newValue`, and if there is not, assume this is a "name changing" event and update the field appropriately. updating fields from change events already has an extra conditional about these VARIABLE fields, but it seems like that would be letting it get kind of out of control.

**Comment by rachel-fenichel** [comment]
I tried this in the blockly playground (renaming a variable from `bar` to `baz`) and got these events:
![image](https://user-images.githubusercontent.com/13686399/32016047-bfaadfd2-b977-11e7-810a-9add034033ca.png)

`oldValue` and `newValue` are both names (not IDs) in both cases.  Seems like that's different from what you're seeing?

I agree that we shouldn't patch around this in the VM, but should just fix it.  I'll keep looking.

**Comment by paulkaplan** [comment]
Are you sure you didn't rename it more than once? If you did it more than once, both old and new are going to look like names, because the first time changes it from id => name, then the second+ time would change it from name => name

**Comment by rachel-fenichel** [comment]
You're right, I had already renamed it so I wasn't seeing the bug.

**Comment by kchadha** [comment]
As of the variables_by_id work in #1350 and because of #1343, there will no longer be a BlockChange event emitted when a variable is renamed. This is because the value of the field_variable/field_variable_getter is no longer changing because it now refers to the associated variable's ID. Renaming a variable only changes the name of the variable, not the underlying ID.
Fixing #1343 will also make it so that renaming a variable won't cause the underlying ID to change because a variable can no longer be renamed to an existing variable.

The issues related to this [scratch-vm#723](https://github.com/LLK/scratch-vm/issues/723) and [scratch-vm#909 ](https://github.com/LLK/scratch-vm/issues/909) are being fixed in [scratch-vm#914](https://github.com/LLK/scratch-vm/pull/914).
