### ISSUE TITLE
Undefined variable appears when deleting variable and changing sprites

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-blocks#1215]
### Expected Behavior

No undefined variables

### Actual Behavior

undefined variable appears

### Steps to Reproduce

1. Go to Data. Create a variable.
2. Drag "set x to" block to workspace
3. In the dropdown, delete variable
You can also delete variables by right clicking on them in the flyout and choosing delete

all appears well

4. Add a new sprite or change to the costume tab
5. Return to the first sprite or the blocks tab

There is now a variable called "undefined"

### Operating System and Browser

Windows 10 Chrome

**Comment by paulkaplan** [comment]
The reason this is happening is because the monitored block for the variable reporter is not being deleted when the variable is deleted. The VM is actually running the opcode for getVariable, which runs a `lookupOrCreateVariable`, emphasis on the **Create** part. The variable was deleted but then re-created. vm/scratch3_data.js only passes the variable ID to `lookupOrCreateVariable`, which is what causes the variable name to appear as `undefined`.

**Comment by paulkaplan** [comment]
@fsih we should move this issue to VM because it is only a vm problem, not scratch-blocks.

**Comment by fsih** [comment]
Moved to https://github.com/LLK/scratch-vm/issues/775. Thanks for investigating!
