### ISSUE TITLE
"tried to start the same gesture twice" and "Trying to cancel a gesture recursively."

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-blocks#1220]
I'm guessing these are logged because they're not supposed to happen? Here is a way to get these to happen.

Trying to cancel a gesture recursively: Drag a block from the workspace to the flyout to delete it.
tried to start the same gesture twice: Click on a block, and while holding down left click, also right click the same spot

**Comment by rachel-fenichel** [comment]
We can remove those logs, but I'll also explain what they're there for.  Wall of text ahead.


--------------
Trying to start the same gesture twice: in an ideal world all mousedowns would have corresponding mouseups. (Same for touch, etc, but that gets into questions of how touch identifiers are generated across platforms.  Let's discuss it in terms of mouse events, because it's easier to talk about.  )

So in the ideal world if you get a second mousedown event and you haven't gotten a mouseup event, you assume that the mousedown was a mistake of some sort and you ignore it, carrying on with the gesture you were previously tracking.

In the real world you can lose a mouseup in a few ways.  On chrome you can reliably do it by mousing down, using the keyboard to change tabs, and mousing up.  The original tab will never know that a mouseup occurred.

Since that would put us into an error state, the compromise is to assume that something went wrong and cancel the previous gesture, then start a new one and associate it with all following mousemove/ups.  And that's fine, but it's a sign that something is weird.  If it's happening a lot, it's likely I'm missing a mouseup in some other way and I want to know that and do something about it.  When I finished the gesture code I wasn't 100% certain that I'd caught every case, so I left the logs in.

_For instance, handling a left click and then a right click with no mouse up in the middle!  That's a case that I hadn't considered, and I'm not sure what the correct behaviour is.  I'm guessing the current code treats it as a right click.  But what about a right click and then a left click before the right click is done?_

But then I added code to make the duplicated block stick to the mouse, and that also probably causes the log.  So there's a lot of noise for any signal, and I haven't seen a lot of new cases besides the one you just brought up, so removing it is fine.

------------

Trying to cancel a gesture recursively: again, this seems like it's a sign that something is wrong with my code if it's happening unexpectedly.  But it's expected when dragging to the flyout to delete: the gesture is ending/cancelling, and says it's time to delete the block it is dragging.  Block dispose checks if the block is a target of an in-progress drag.  If it is, it cancels the drag...which then tries to dispose of the block.  

There's a check to break the cycle, but I wanted to know if there were recursive calls that I wasn't expecting (not during deletion on the flyout, for instance).  So I left a log to keep an eye out for weird cases.  Nothing major has cropped up in the last few months, so I'm also fine with removing that one.

**Comment by fsih** [comment]
Thanks for the info, the mouse up/down stuff will be useful to know! Personally, I don't think it's a big deal to leave in the logging, though the block deleting one is pretty common and it might be good to not show it if we expect it.

**Comment by rachel-fenichel** [comment]
We can probably remove these logs now.  Dragging seems to have stabilized, so now they're just noise.
