### ISSUE TITLE
Pen is an extension

### ISSUE THREAD

**Issue by chexbox** [LLK/scratch-blocks#1249]
Pen should not be an extension since it isn't in any of the previous versions of scratch.
I hope that we can update this as I think many new users will have a hard time finding this powerful tool. Off-topic: Can scratch 3 read sb2 files?
Operating System and Browser:

Mac OS 10.11.6 Firefox 57.0

**Comment by towerofnix** [comment]
>Pen should not be an extension since it isn't in any of the previous versions of scratch.

Counter-argument: In Scratch 1.4 (and earlier), there was only a Control category. In Scratch 2.0, it got split into Control and Events. Nothing bad happened inherently because it was different. (At most, maybe a few users were surprised, and had to get used to it.. which, for the most part, probably took not more than an hour of programming in 2.0.)

>Off-topic: Can scratch 3 read sb2 files?

Yes. I'm not sure there's a way to upload an SB2 into the GUI directly from your file system, but you can pass a project ID at the end of the URL, inside the hash-part: `llk.github.io/scratch-gui/#project_id`

**Comment by thisandagain** [comment]
Please see discussion in https://github.com/LLK/scratch-gui/issues/725

**Comment by thisandagain** [comment]
Yes, Scratch 3.0 can read SB2 files.

**Comment by ghost** [comment]
I still don't think that it made sense to move pen to extensions. We've been told that it's "not good for beginners", but personally I think it would be better for beginners - by moving them to extensions, beginners will be less likely to find them. 

The extensions were originally for connecting Scratch to physical objects, and it should stay that way.
