### ISSUE TITLE
Deleting a procedure definition should remove the call block from the palette

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-blocks#1295]
Scratch 2
![scratch-2](https://user-images.githubusercontent.com/654102/33632479-b86f3c52-d9db-11e7-8950-515d7916cf14.gif)

Scratch 3
![scratch-3](https://user-images.githubusercontent.com/654102/33632484-bc026196-d9db-11e7-8b33-4ec658065af1.gif)

Unlike with variables, we don't have a specific callback for this, since it is just a standard block delete. So I'm not exactly sure where this behavior should live. @rachel-fenichel should it live outside in the vm/gui? Or is there a specific way to refresh the toolbox on the define block delete?

**Comment by AmazingMech2418** [comment]
I think there needs to be a JS array that can store all of the blocks and show only the ones that are active in the palette. Maybe something like this to delete the block:
var customs=[]; function customdelete(block) { customs.splice(customs.indexOf(block),1); }
Then, adding blocks would just have to add the id to the array "customs" and add a function where if the x position of the block definition is in the palette, it will delete the block with the code. I just copied this from the last version. I think it could work.

**Comment by RoboErikG** [comment]
I think in Blockly it checks the workspace for procedure_def and procedure_def_noreturn blocks every time you open the procedures flyout (which is probably the wrong way to handle it in Scratch).

Since we have events now you could register an event listener that updates the list of available procedures when those blocks are created or deleted.

**Comment by AmazingMech2418** [comment]
I think that would work.
