### ISSUE TITLE
Adjust scrollbars on touch devices

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#1344]
### Expected Behavior

- Scrollbars should either be gone or of a reasonable size

### Actual Behavior

- Scrollbars are comically large

### Steps to Reproduce

- Open GUI on a touch device (iPad, Android Tablet, or Chrome Book w/ Touch Screen)

**Comment by rachel-fenichel** [comment]
If you want them to not be comically large, here's the line to tweak: https://github.com/LLK/scratch-blocks/blob/develop/core/scrollbar.js#L302

But note that they're large to make them better touch targets.  And they are visible to help a user orient themselves in the workspace, since it can extend in all directions.
