### ISSUE TITLE
Soft Keyboard doesn't stay open on block inputs

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-blocks#1345]
Device: Pixel C, Android 8.0, Chrome

Steps to repro:

Say block, touch input area, keyboard opens and immediately hides again
Make a block dialog, touch block name input, keyboard opens and immediately hides. (also happens for inputs)

**Comment by rachel-fenichel** [comment]
This is in scratch-blocks but not blockly, probably because blockly just uses a pop-up to get text on mobile.

**Comment by xys1836** [comment]
It seems that Android keyboard will change the size of windows and dispatch the workspace resize event. So I try to comment the `Blockly.hideChaff(true);`  in scratch-blocks/core/inject.js.
As shown follows:
```
  var workspaceResizeHandler = Blockly.bindEventWithChecks_(window, 'resize',
      null,
      function() {
        // Blockly.hideChaff(true);
        Blockly.svgResize(mainWorkspace);
      });
```
It causes some other problems such as the text input filed will not follow with the block but stay the same place while inputing texts. But at least it works on Android devices.

**Comment by rachel-fenichel** [comment]
FYI I'm seeing a lot of reports of this in user feedback on the preview.

**Comment by howettl** [comment]
Hello @rachel-fenichel or @thisandagain , is there an ETA on when this bug might be fixed? Alternatively, do you have any suggestions about how we might be able to work around it?

**Comment by thisandagain** [comment]
@howettl We'll need to get to this before August, but I'm guessing this may get scheduled for June. I'd need to dive more deeply into the codebase to figure out where it is happening.

**Comment by picklesrus** [comment]
I don't have a touch device I can test with this week so apologies for a bunch of stack overflow links that I can't actually verify myself.... but I think I learned some things that might be worth sharing.

I think @rachel-fenichel is right that Blockly avoids this because it uses prompt on mobile (https://github.com/google/blockly/blob/master/core/field_textinput.js#L160) and the comment indicates that's because mobile browsers are finicky with focus.

Also, @xys1836's theory that there's a window resize event caused by the keyboard opening seems plausible. I don't know if there's a way to detect that in the resize handler though :-(. This was the best suggested solution I I've found so far, but it makes me nervous: https://stackoverflow.com/questions/14902321/how-to-determine-if-a-resize-event-was-triggered-by-soft-keyboard-in-mobile-brow 

I dug around to see if non-scratch-blocks text inputs that trigger the keyboard (e.g. the sprite name, coordinates, etc.) also made the keyboard disappear. They don't, but that sort of breaks my model of the window resize event being the problem :(

**Comment by chrisgarrity** [comment]
Also exhibited on Edge/Surface

**Comment by AnmAtAnm** [comment]
This issue was filed here as an Android issue, but I want to call attention to https://github.com/google/blockly/issues/1843 filed by @paulkaplan that relates to Edge.  I didn't find a similar issue for the Edge case, which affects the current beta (tested on a Surface).

I have not been able to reproduce that bug in either Scratch or Blockly in the Chrome browser on the same Surface.

**Comment by picklesrus** [comment]
This is probably the same as  https://github.com/LLK/scratch-gui/issues/2692, but keeping both for now since in case it is an interaction of the blocks input and gui resizing.
