### ISSUE TITLE
After block disconnection, undo and redo don't restore the blocks' state properly 

### ISSUE THREAD

**Issue by brassaro** [LLK/scratch-blocks#1347]
### Expected Behavior

After performing an action, using UNDO should but the blocks in the state they were before the action; using REDO after the UNDO should put the blocks back in the state they were after the action.

### Actual Behavior

After performing an action like disconnecting a block from a stack of block, pressing UNDO then REDO causes the blocks to weird positions, and even sometimes disconnect

### Steps to Reproduce

1- Use the vertical_playgroud.html. Start with a fresh empty workspace.
2- Connect 3 statement blocks (for example, connect 'move X steps', 'turn right Y degrees', and 'turn left Z degrees').
3- Drag and disconnect the 2nd block in the stack of blocks. Release it away from the 1st block so that it now forms a new stack of blocks.
4- Press UNDO; notice the blocks reconnect as expected
5- Press REDO; notice that the blocks disconnect as expected, but that the position of the blocks that were dragged away from the 1st block is different than at step 3
6- Press UNDO; notice how the blocks' positions are not properly restored to be like in step 2
7- Press UNDO/REDO more and notice how the position is different from steps 2 and 3.

### Operating System and Browser

Mac OS 10.12.6 (16G1114), Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by xys1836** [comment]
Another similar bug shown as the following gif figure.
1. Drag four operator blocks(for example, +, -, *, /)
2. Align them in the workspace from top to bottom.
3. Insert the block to another block in opposite order (/, *, -, +)
4. Press undo, notice the blocks perform as expected.(actually the position is wrong)
5. Press undo again, notice the layout of blocks broken.

This also happens by pressing command+z on MacOS.


![bugs](https://user-images.githubusercontent.com/5347269/35777658-2919ee54-09f5-11e8-9458-90f3353a1abf.gif)

**Comment by BryceLTaylor** [comment]
I tried this two different ways.  I got the same results on Preview and Develop.   If I do the initial redo by right clicking the workspace and choosing redo then everything behaves as normal. 

1. Navigate to the gui
2. drag 3 blocks into the workspace, connecting them.
3. disconnect a block, dragging it to the side, leaving it on the workspace
4. right click the stage
5. select undo from the menu
(Instead of 4 and 5 you could press cmd-z on the mac. Fine for this step but not below.)
*NOTE the  block has returned to the original position, attached 

6. Right click on the workspace.
7. select redo on the dropdown.
8. NOTE that the block returns to where you had dragged it.  This checks out but look below. 

![undoblocksrightclick](https://user-images.githubusercontent.com/1088291/37097220-dcd82090-21e8-11e8-8d02-72695bcb85c8.gif)

6a. press shift-cmd-z on the keyboard (mac).
7a. Note, the block has gone somewhere crazy.  From here on it doesn't matter which method you use for undo or redo, the blocks go to unpredictable places.

![undoblockscmdz](https://user-images.githubusercontent.com/1088291/37097232-e5f06c82-21e8-11e8-8a03-10714b2d61a8.gif)

Also, if you had used the drop down to undo the first time then shift-cmd-z will behave normally in the future.

(steps 1-7 below are the same as in the first example above)
1. Navigate to the gui
2. drag 3 blocks into the workspace, connecting them.
3. disconnect a block, dragging it to the side, leaving it on the workspace
4. right click the stage
5. select undo from the menu
(Instead of 4 and 5 you could press cmd-z on the mac.)
6. Right click on the workspace.
7. select redo on the dropdown.
8. press cmd-z (mac)
9. Note the blocks go to their pre-separated positions.
10. press shift-cmd-z (mac)
11. Note the blocks go to their expected post-separated positions.

It seems that the two methods for re-do are different.  It also seems that once you have done a re-do both re-do methods will reproduce the original action.  It appears to be a problem with creating that event.

**Comment by picklesrus** [comment]
I can't repro this anymore. Closing!
