### ISSUE TITLE
Button text is improperly aligned on Firefox

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#1352]
![image](https://user-images.githubusercontent.com/747641/35123733-7ae77c24-fc71-11e7-9e29-f4fb5e603528.png)

**Comment by rachel-fenichel** [comment]
Code pointer: https://github.com/LLK/scratch-blocks/blob/develop/core/flyout_button.js#L176

**Comment by radioblahaj** [comment]
What Needs to be fixed?

**Comment by thisandagain** [comment]
The text within each button (see "Make a Block") is not vertically aligned within the button bounds on Firefox. It should look like this:
![image](https://user-images.githubusercontent.com/747641/35708876-260ad04e-077e-11e8-88d5-bc84229628e6.png)

**Comment by radioblahaj** [comment]
Where is the code?

**Comment by samelhusseini** [comment]
Fix here is to use dominant-baseline instead of alignment-baseline here: https://github.com/LLK/scratch-blocks/blob/develop/core/flyout_button.js#L177

For Edge you'll have to use dx as they don't support any of the SVG alignment attributes. 
Similar to how it was done https://github.com/LLK/scratch-blocks/pull/1340

If I get some time I'll create a PR
