### ISSUE TITLE
Blocks can be duplicated in the blocks list by keyboard

### ISSUE THREAD

**Issue by xys1836** [LLK/scratch-blocks#1373]
1. Single click on any block in the blocks list.
2. Press command + c, then command + v  on MacOS (ctrl+c and ctrl+v on Windows)
3. The block clicked just now will be duplicated in the block list and the duplicated block cannot be removed.

Notice that the block "when green flag clicked" duplicated by command + c and command + v .  in the following figure.

<img width="379" alt="screen shot 0030-02-04 at 21 33 49" src="https://user-images.githubusercontent.com/5347269/35777581-b41d6b5e-09f3-11e8-9b9b-a4e660029f9e.png">

**Comment by rachel-fenichel** [comment]
This is my new favorite bug.

It also exists in blockly--you can get it to happen in the playground with a simple toolbox. 

The solution is pretty simple.  Cut (ctrl/command-x) and paste (ctrl/command-v) should definitely not work in the flyout.  We can add a flyout check [here](https://github.com/google/blockly/blob/master/core/blockly.js#L209) and [here](https://github.com/google/blockly/blob/master/core/blockly.js#L217).

We could either disallow copying from the flyout (with the keyboard) or make it so that something copied from the flyout is always pasted into the main workspace.

@quachtina96 I think this is relevant for being able to do keyboard work in and around the flyout.  Do you have any thoughts on this?

**Comment by quachtina96** [comment]
I think it'd be great to make things copied from the flyout always paste into the workspace. In discussions I've had, the flow for grabbing a block from the toolbox and putting it into the workspace is very similar to the copy-paste flow in things like Excel or spreadsheets.

**Comment by rachel-fenichel** [comment]
Oh sweet, you can also delete blocks in the flyout with backspace and delete, at least on blockly.

**Comment by Kenny2github** [comment]
I think that keyboard c&p&d is great, just not when it copies into or deletes from the flyout. I'd say pasting should always paste into the workspace, and deleting should not work at all in the flyout.

**Comment by rachel-fenichel** [comment]
@Kenny2github yeah I'm fixing it right now on Blockly, with that behaviour.

**Comment by rachel-fenichel** [comment]
For completeness: trying to cut (ctrl/cmd+x) in a flyout will not delete the block, and it also won't copy it to the clipboard.  That matches behaviour when trying to cut uncuttable text in the browser.

**Comment by rachel-fenichel** [comment]
Fixed upstream.

**Comment by king2022new** [comment]
`<script>alert(1)</script>`
