### ISSUE TITLE
Bring horizontal dropdown input states to spec

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-blocks#148]
## Horizontal: Sizing / Radius
**Alignment has more nuance based on the block type. e.g Hat Block vs Default Block**
![r4_event-menu-cap size](https://cloud.githubusercontent.com/assets/3409578/14120931/122622fa-f5c3-11e5-8a37-4bb7b0c8e01c.png)
![r4_event-menu-cap radius](https://cloud.githubusercontent.com/assets/3409578/14120949/23520a1c-f5c3-11e5-8245-d7785188a0fa.png)

## Sizing: Default / Focus 
![r1_dropdown-input-focusing](https://cloud.githubusercontent.com/assets/3409578/14120963/3af0f2e6-f5c3-11e5-90e3-5fe1efd7f448.jpg)

**Once the user makes selection from the menu the block will update.**
- Horizontal: The icon switches to the newly selected option 
- Vertical: The string switches to the newly selected option.

## Color: Default / Focus
![r1_dropdown-input-colors](https://cloud.githubusercontent.com/assets/3409578/14121020/a457f86a-f5c3-11e5-86b3-78502e0acdf4.jpg)
![r1_horizontal-colors](https://cloud.githubusercontent.com/assets/3409578/14121025/a8493e02-f5c3-11e5-917d-9d9a8748ab9f.jpg)

## Input: Desktop / Device
![r1_dropdown-input-focusing](https://cloud.githubusercontent.com/assets/3409578/14121030/b37af748-f5c3-11e5-948f-6e06216ce727.jpg)

**Comment by tmickel** [comment]
@carljbowman:
I recommend we drop this as it's tremendously technically difficult to pull off the animated stroke as it was done for the text inputs. To do so essentially requires the reproduction and floating of HTML/CSS for the entire clickable field on top of the SVG. That's what we did for the text inputs - since it was already needed for typing. We could also add an animated stroke on the SVG, but it won't match the look of the text inputs, since SVG can only stroke on the center of the path (in CSS we are doing outside the path).

Here is my latest implementation with color changing:

Horizontal, before:
<img width="89" alt="screen shot 2016-10-04 at 5 32 49 pm" src="https://cloud.githubusercontent.com/assets/120403/19093333/b0b4979c-8a58-11e6-8460-4582baaf466b.png">
Horizontal, after:
<img width="231" alt="screen shot 2016-10-04 at 5 32 53 pm" src="https://cloud.githubusercontent.com/assets/120403/19093336/b5b1e93e-8a58-11e6-9d50-f5c82b4ac34b.png">
Vertical droppable, before:
<img width="262" alt="screen shot 2016-10-04 at 5 33 05 pm" src="https://cloud.githubusercontent.com/assets/120403/19093348/c1a0e6be-8a58-11e6-816f-435c7292259b.png">
Vertical droppable, after:
<img width="287" alt="screen shot 2016-10-04 at 5 33 08 pm" src="https://cloud.githubusercontent.com/assets/120403/19093352/c71ece26-8a58-11e6-93d8-7dae2a2fcda1.png">
Vertical undroppable, before:
<img width="228" alt="screen shot 2016-10-04 at 5 33 14 pm" src="https://cloud.githubusercontent.com/assets/120403/19093357/ce91e67a-8a58-11e6-8cda-aa8219ab729b.png">
Vertical undroppable, after:
<img width="281" alt="screen shot 2016-10-04 at 5 33 18 pm" src="https://cloud.githubusercontent.com/assets/120403/19093369/d4c49772-8a58-11e6-9bd4-d629b98dd244.png">
