### ISSUE TITLE
Cannot edit the text of a comment on touch devices

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-blocks#1631]
### Expected Behavior

Should be able to edit the text of a comment.

### Actual Behavior

Cannot edit the text of a comment on a touch device.

**Comment by picklesrus** [comment]
Workspace comments are editable, though block ones aren't.

**Comment by picklesrus** [comment]
A few things I've learned:
Block comments and workspace comments have slightly different svg structures.  Because of that, the mouse/touch handling code acts a little differently. E.g. workspace comments actually interact with the Gesture class and bubbles, block comments, at least for focus, do not.

The simple thing to do is to make block comments set focus on mousedown events instead of on mouseup events. That makes things work on android touch devices. However, Firefox would then require 2 clicks to be able to edit the comment instead of just one.  In the short term this seems like a worthwhile tradeoff to me.

**Comment by picklesrus** [comment]
I'm going to go ahead and do the simple thing for now because I learned some things and fixing them has implications I don't have time for at the moment.  Here's my brain dump:

[setTextArea](https://github.com/LLK/scratch-blocks/blob/develop/core/comment.js#L223) focus on the Comment class gets called on mouseup and is bound [here](https://github.com/LLK/scratch-blocks/blob/develop/core/comment.js#L126).  It is bound on mouse up due to the previously mentioned FIrefox problem.

In order to fix that, the right thing to do is probably to bind on mouse down and let the code proceed through the usual gesture handling class.  That means doing something more like what workspace_comment_svg does in [pathMouseDown](https://github.com/LLK/scratch-blocks/blob/develop/core/workspace_comment_svg.js#L157) i.e.
` var gesture = this.workspace.getGesture(e);
  if (gesture) {
    gesture.handleBubbleStart(.....);
  }`

But, because the mousedown is on a text area (and utils.isTargetInput returns true, [doStart](https://github.com/LLK/scratch-blocks/blob/develop/core/gesture.js#L484) gives up and cancels the gesture.  I believe this is why the workspace comment has layer of svg in it. I think that layer catches the bubble click and gets it past the target input check.  

Next, even if we fixed that, by the time we decide this was a bubble click gesture's [handleUp](https://github.com/LLK/scratch-blocks/blob/develop/core/gesture.js#L590), [doBubbleClick](https://github.com/LLK/scratch-blocks/blob/develop/core/gesture.js#L720) tries to call startBubble_.setFocus(). Except, startBubble_ (which is of type ScratchBubble)  doesn't have the setFocus method on it. Only WorkspaceCommentSvg has this [method](https://github.com/LLK/scratch-blocks/blob/develop/core/workspace_comment_render_svg.js#L662). It turns out, in the case of workspace comments, the startBubble_ member variable ***isn't*** a Bubble or a subclass of Bubble. Instead, it just happens to have the setFocus method focus and works. So, we have some mess to clean up.  I haven't internalized the reach of cleaning it up yet so I'm going to put this aside for now.

**Comment by picklesrus** [comment]
> I'm going to go ahead and do the simple thing for now because I learned some things and fixing them has implications I don't have time for at the moment. Here's my brain dump:
> 
> [setTextArea](https://github.com/LLK/scratch-blocks/blob/develop/core/comment.js#L223) focus on the Comment class gets called on mouseup and is bound [here](https://github.com/LLK/scratch-blocks/blob/develop/core/comment.js#L126). It is bound on mouse up due to the previously mentioned FIrefox problem.
> 
> In order to fix that, the right thing to do is probably to bind on mouse down and let the code proceed through the usual gesture handling class. That means doing something more like what workspace_comment_svg does in [pathMouseDown](https://github.com/LLK/scratch-blocks/blob/develop/core/workspace_comment_svg.js#L157) i.e.
> ` var gesture = this.workspace.getGesture(e); if (gesture) { gesture.handleBubbleStart(.....); }`
> 
> But, because the mousedown is on a text area (and utils.isTargetInput returns true, [doStart](https://github.com/LLK/scratch-blocks/blob/develop/core/gesture.js#L484) gives up and cancels the gesture. I believe this is why the workspace comment has layer of svg in it. I think that layer catches the bubble click and gets it past the target input check.
> 
> Next, even if we fixed that, by the time we decide this was a bubble click gesture's [handleUp](https://github.com/LLK/scratch-blocks/blob/develop/core/gesture.js#L590), [doBubbleClick](https://github.com/LLK/scratch-blocks/blob/develop/core/gesture.js#L720) tries to call startBubble_.setFocus(). Except, startBubble_ (which is of type ScratchBubble) doesn't have the setFocus method on it. Only WorkspaceCommentSvg has this [method](https://github.com/LLK/scratch-blocks/blob/develop/core/workspace_comment_render_svg.js#L662). It turns out, in the case of workspace comments, the startBubble_ member variable _**isn't**_ a Bubble or a subclass of Bubble. Instead, it just happens to have the setFocus method focus and works. So, we have some mess to clean up. I haven't internalized the reach of cleaning it up yet so I'm going to put this aside for now.
