### ISSUE TITLE
Duplicating a stack causes the blocks workspace to be unresponsive

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-blocks#1647]
### Expected Behavior

After duplicating a stack of blocks they should appear on the workspace and you should be able to continue to work.

### Actual Behavior

After long tapping and duplicating the blocks nothing happens on the stage.  The new blocks appear exactly above the old blocks and they can not be moved.  No other blocks can be moved in the workspace and no blocks can be dragged from the blocks pallet to the workspace.

If you select the stage and then go back to the sprite where the code was duplicated you can now edit blocks again.

### Steps to Reproduce

Build a stack of blocks
Press and hold on the stack of blocks
Select Duplicate from the menu that appears
Note: the menu closes and it might look like no new blocks appear or that they appear right on top of the old blocks.
Try to drag blocks on the stage and add new blocks to the workspace
Note: You can't

There was another issue with duplication on android that this may be related to: https://github.com/LLK/scratch-gui/issues/2376

### Operating System and Browser

Chrome on Android

**Comment by jorenl** [comment]
I have experienced behavior similar to this and to the other issue referenced using Chrome on Windows. (but can't consistently reproduce). Duplicating does, however, consistently throw errors as reported in #1550 - could that be related?

**Comment by BryceLTaylor** [comment]
I've seen this on iPad as well. https://github.com/LLK/scratch-gui/issues/2995

**Comment by hecor** [comment]
This happens on mobile devices. It's probably caused by the drag fakeEvent as we don't have mouse on mobile devices, when I comment the following line in  core/block_svg.js 
`// ws.startDragWithFakeEvent(fakeEvent, newBlock);
`
the problem will disappear, and the duplicated blocks is just on top of original blocks, in order to make the duplicated blocks more obviously, I changed
`newBlock.moveBy(oldBlockPosWs.x, oldBlockPosWs.y);
`
to 
`newBlock.moveBy(oldBlockPosWs.x+30, oldBlockPosWs.y+30);
`
It's just my way to fix this issue, and I think the user experience is not bad.

**Comment by rachel-fenichel** [comment]
As @hecor mentioned, the problem is that it's kicking off another drag immediately, which woul dnormally stick with the mouse as it moves.  There is no mouse move to track in touch, and there's no indication that you're already in a drag and will therefore ignore some following touches.

If we just want to do something different in the mouse vs touch cases, we can do that by changing the callback on the context menu option.

[This line](https://github.com/LLK/scratch-blocks/blob/develop/core/block_svg.js#L673) in block_svg is the last time we have access to an event that distinguishes between mouse and touch.

[Blockly.ContextMenu.blockDuplicateOption](https://github.com/LLK/scratch-blocks/blob/develop/core/contextmenu.js#L263) takes in a block and hands back a context menu item with a callback, which is defined by [Blockly.scratchBlocksUtil.duplicateAndDragCallback](https://github.com/LLK/scratch-blocks/blob/develop/core/scratch_blocks_utils.js#L170).  Note that inside the callback function, `e` is not a Mouse or Touch Event--it's something else that comes from the menu.

To make the change, we would pass an `isTouch` boolean or equivalent into `blockDuplicateOption`, which would pass it into `duplicateAndDragCallback`, which would return a function that behaves differently in the mouse case from the touch case.

If we want to do this, we need to decide where the newly created blocks should go--presumably at some offset from the originals, at minimum.
