### ISSUE TITLE
Custom block deformation with Magyar language

### ISSUE THREAD

**Issue by ZenithRogue** [LLK/scratch-blocks#1658]
Custom block definitions become deformed when used with the Magyar language. This deformation causes a second of text to appear below the first. This also causes the bottom right corner to no-longer be rounded. This only affects custom block definitions, not any other block type. (as I am presently aware)

Deformation illustrated below:
![deformed blocks](https://user-images.githubusercontent.com/11393734/43040831-fe135f90-8d13-11e8-84de-b094cc2ccfb7.png)

I am not currently aware of any other languages in which this occurs, but I will continue to check.

**Comment by ZenithRogue** [comment]
Edit: This also affects Korean, causing all text to appear below the block
![deformed blocks](https://user-images.githubusercontent.com/11393734/43040857-069722ea-8d15-11e8-9417-122cc697c165.png)

**Comment by Kenny2github** [comment]
I suspect this is because the block definition... block doesn't handle text *after* the custom block correctly, not realizing that some languages must have text after it.

**Comment by rachel-fenichel** [comment]
@Kenny2github that's right.  In particular, the block looks like it has two inputs in its internal representation.  The first line is a text + statement input (rendered strangely).  The next line is a dummy input.  A statement input always causes the following stuff to jump to a new line, like in all of these.
![image](https://user-images.githubusercontent.com/13686399/43090807-46afaa8e-8e5d-11e8-96e0-7bbdeb0b0499.png)

Splitting into rows is done in [renderCompute_](https://github.com/LLK/scratch-blocks/blob/develop/core/block_render_svg_vertical.js#L775).  The solution _might_ be to modify that code to be aware of define blocks and only make one row in a define block, no matter what.

The define block has some pretty custom rendering, because it has a fully rendered statement block inside it.

I don't have a quick fix, but here's the code for rendering this block: https://github.com/LLK/scratch-blocks/blob/develop/core/block_render_svg_vertical.js#L1579

Called from here: https://github.com/LLK/scratch-blocks/blob/develop/core/block_render_svg_vertical.js#L1335
