### ISSUE TITLE
build.py requires Python 2.x whose EOL date is 2020

### ISSUE THREAD

**Issue by nekketsuuu** [LLK/scratch-blocks#1679]
### Expected Behavior

We can build and install scratch-blocks using Python 3.x.

### Actual Behavior

`build.py` requires to use Python 2.x. See [these lines](https://github.com/LLK/scratch-blocks/blob/f5ff6029c223f0f136afe6f9070a267841a42844/build.py#L38).

[PEP 373](https://legacy.python.org/dev/peps/pep-0373/) and <https://pythonclock.org/> says the End Of Life date of Python 2.x is January 1st, 2020. Therefore we should use Python 3.x instead in order to enjoy official security patches quickly.

Is there any plan to update the script?

**Comment by Kenny2github** [comment]
Though Python 2.7 is not going to be maintained, it will still be available to download and use. If the current script works in Python 2, it will continue working past 2020. There is no need to update the script just because a new version is out - obviously, since the script hasn't already been updated, none of the features of the new version are required for the script to work. This is a complete non-issue.

**Comment by nekketsuuu** [comment]
@Kenny2github I cannot agree with your opinion because `build.py` uses a network library around [this line](https://github.com/LLK/scratch-blocks/blob/f5ff6029c223f0f136afe6f9070a267841a42844/build.py#L399) to use Closure compiler on remote. Therefore the security assurance is needed.

Moreover, these days it's a little harder to install Python 2.x as `python` command than to install 3.x as it. For instance, [`brew install python` installs 3.x now](https://brew.sh/2018/01/19/homebrew-1.5.0/).

**Comment by Kenny2github** [comment]
That line only uses the Python standard library module "[httplib](https://docs.python.org/2/library/httplib.html)", which has merely been renamed to "[http.client](https://docs.python.org/3/library/http.client.html)" in Python 3. The script does not use any third-party libraries at all, and there is no difference in security levels between httplib and http.client.

Looking at that article you linked, `brew install python@2` on macOS will do the trick. It's only 2 extra characters. On Windows, you can simply navigate to the [python.org downloads page](https://www.python.org/downloads/windows/) for a Windows py2.7 installer. On Linux, it depends on the distribution, but at least for Debian, "python" remains version 2.7 and "python3" is 3.5.

**Comment by joker314** [comment]
@Kenny2github The point is not that Python 3 is more secure than Python 2 right now. It's that when a security vulnerability is found in the HTTP library, Python 2 might not be updated (but Python 3 will).

**Comment by Kenny2github** [comment]
@joker314 you say "when" as if it's inevitable? *If* a security vulnerability is found, only then will it be time to update the script. There's no need to update it *nownownow*.

**Comment by nekketsuuu** [comment]
@Kenny2github It's too late to update the script after a vulnerability is found. We should follow updates as much as possible in order to protect our software from *possible* attacks. For example, we should update our anti-virus software *before* a virus is found, shouldn't it?

Yes, Python 2.7's `httplib` is considered safe until 2020, but its safety is not guaranteed after Jan. 1, 2020. The official support ends in the not-so-distant future. So I think it's a good time to consider when we update the script. Therefore I asked this question here because I don't know if there is already an update plan or a PR.

**Comment by joker314** [comment]
@Kenny2github "[W]hen", specifically because all software has security vulnerabilities, it's just a matter of the wait before they are found.

What are the losses of acting? Some lost time.

Yet the losses of inaction are much greater -- and we do have an ethical responsibility to eradicate them. To say that we can retroactively patch the problem after it's been publicly announced is to forget about the time it takes to create that patch, and the time it takes to disclose the vulnerability.

(Some vulnerabilities have patches created first, then they are announced, to minimise the impact. I believe this is what happened when the speculative execution attacks were discovered for Linux.)

Due to the way computers allow programs to access everything under the user's privileges, we have to assume the worst case: work could be lost, **and sensitive personal information is disclosed**. That's not okay if it happens. 

We have three years to prevent serious issues, that's less than 10 seconds a day if the fix takes an hour.

**EDIT**: When I said "speculative execution for Linux", I did not mean that speculative execution vulnerabilities _only_ affected Linux.

**Comment by Kenny2github** [comment]
Okay, you've made your points, and I see why you're all so anxious. This issue would still best fit in Backlog, nonetheless.

**Comment by rachel-fenichel** [comment]
See https://github.com/google/blockly/pull/2123 and https://github.com/google/blockly/pull/2125

**Comment by tansly** [comment]
Just to add to the discussion: Python 2 being unmaintained is not my only concern. Some Linux distros are already [discussing whether to point the `python` command to Python 3 instead of Python 2](https://lwn.net/Articles/792718/).
Python 3 becoming the default version for the `python` command will break the build. Although it is not hard to point the build script to Python 2, this will be a bad user experience. Plus, Python 2 is already dropped from the default installation of some Linux distros (i.e. Fedora) so in order to build scratch-blocks, a user must manually install Python 2, whereas Python 3 is installed by default. Not to mention Python 2 may be totally dropped from the official repositories of some Linux distros in the upcoming years,

**Comment by cymplecy** [comment]
I just came across this issue - on my Win10 machine python defaults to python3 so the build fails.

I have python2 on my machine as well

Where is build.py called from- if I knew that - I think I could edit it to use c:\python27\python.exe instead

**Comment by tansly** [comment]
Just a heads up: Fedora 31 is released recently and it defaults `python` to Python 3. I would expect that other Linux distros to follow shortly, so this issue will cause more breakage soon. As @cymplecy notes, it already breaks in Windows as well.

@cymplecy you can check `package.json` file, it should contain a line calling `python`. Changing that to `python2` could work as a workaround.

**Comment by cymplecy** [comment]
@tansly Thanks for pointer - amended package.json to use c:/python27/python.exe build.py but now getting error that it can't find subprocess.lib
```
> c:/python27/python.exe build.py && webpack

Traceback (most recent call last):
  File "build.py", line 574, in <module>
    test_proc = subprocess.Popen(test_args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "c:\python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "c:\python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

**Comment by cymplecy** [comment]
I tried running build.py thru the 2to3 convertor - still got an error about not finding subprocess.py :(

**Comment by cymplecy** [comment]
Luckily for me, as I'm only working on an extension, I've found I don't need scratch-blocks - only scratch-vm and scratch-gui so I've avoided this bullet

**Comment by tansly** [comment]
Hey again,

> @tansly Thanks for pointer - amended package.json to use c:/python27/python.exe build.py but now getting error that it can't find subprocess.lib
> 
> ```
> > c:/python27/python.exe build.py && webpack
> 
> Traceback (most recent call last):
>   File "build.py", line 574, in <module>
>     test_proc = subprocess.Popen(test_args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
>   File "c:\python27\lib\subprocess.py", line 394, in __init__
>     errread, errwrite)
>   File "c:\python27\lib\subprocess.py", line 644, in _execute_child
>     startupinfo)
> WindowsError: [Error 2] The system cannot find the file specified
> ```

The issue you are facing could be https://github.com/LLK/scratch-blocks/issues/1859. Or you have closure compiler missing (check the [wiki](https://github.com/LLK/scratch-blocks/wiki)).
In this case the error is not related to Python 3 support.

**Comment by thebravoman** [comment]
Python2 is inconvenient. I have read the thread and seen the arguments for maintaining last versions and security. Although they are important I would like to suggest moving to python3 for developers productivity. 

My case is that I am managing a pretty large python infrastructure and got scratch-blocks to play around. I have spent the last years actively moving out of python2 for production projects. 

Now I get scratch-blocks to play around, build some blocks, probably contribute and solve an issue because I really like the project and I am surprised by the 

```
npm ERR! code 127
npm ERR! path /Users/kireto/axles/code/scratch-blocks
npm ERR! command failed
npm ERR! command sh -c python build.py && webpack
```

Now I have to again add python2 to my machine and manage both of them and we know what a mess this could be. Yes, I will manage. Yes, there is a way. But is an additional wall for people to just download and play around and get involved. 

Additionally some of the previously mentioned solutions like
```
$ brew install python@2
Warning: No available formula with the name "python@2". Did you mean ipython, bpython, cython or jython?
==> Searching for similarly named formulae...
These similarly named formulae were found:
ipython                                              bpython                                              cython                                               jython
To install one of them, run (for example):
  brew install ipython
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

```
don't work. So for someone now starting it might be a difficult to get it working.
 
I could probably take and migrate build.py it to python3. 

Would this be accepted as a PR?

**Comment by tansly** [comment]
We had a PR back then (from 2019) here: https://github.com/LLK/scratch-blocks/pull/1964

There was a [discussion to put it in the queue to review](https://github.com/LLK/scratch-blocks/pull/1964#issuecomment-665270880) but I haven't been following closely since then.

**Comment by thebravoman** [comment]
Thanks @tansly 

I've seen the script.
From what I can see it calls closure library locally or the remote service and this could be achieved in python3 and in bash or in JS and node. 

The discussion does not bring more light. The PR you've proposed makes sense. What do you think is stopping it from being merged? Should we involve someone into the discussion?
