### ISSUE TITLE
Create a custom block with the sprite list as an input

### ISSUE THREAD

**Issue by MisinformedDNA** [LLK/scratch-blocks#1805]
I'd like to create a custom block that accepts a "sprite list" as an input. For instance, I'd like to create a block that is "move towards [sprite]" similar to how "point towards [sprite]" or "go to [sprite]" work. As far as I can tell, custom blocks only allow for string, number or boolean inputs. Am I missing something, or can this be added as a feature request?

**Comment by Wowfunhappy** [comment]
You can use a string as input.

![Screen Shot 2022-12-09 at 6 54 25 PM](https://user-images.githubusercontent.com/4484096/206813614-462b01c3-099e-44c2-81ff-a1370edcfc54.png)

The above code will work if you have a sprite named "Avery" in your program.

**Comment by cwillisf** [comment]
Thanks for the help, @Wowfunhappy! That's what I would recommend as well. It's worth noting that this solution isn't very obvious, so that's a valuable usability comment. Thank you both!

I think it could be fun to add more kinds of inputs for "My Blocks," but we also need to balance the complexity of an already complicated process. If we add an input for sprites, should we also add an input for costumes, backdrops, sounds, messages, or keys? Maybe we should add some or all of those! Or maybe it would make the "Make a Block" dialog too cluttered and confusing for younger Scratchers.

Because of the potential for added complexity, we're more likely to focus on changes that make things possible where they're currently impossible -- for example, #1866. I'll close this one for now, but thanks for the suggestion!
