### ISSUE TITLE
Paint editor: Vertical flip rotates

### ISSUE THREAD

**Issue by gunchleoc** [LLK/scratch-blocks#1842]
Just in case it wasn't implemented like this on purpose:

### Expected Behavior

When clicking the "Flip Vertically" button in the paint editor, the costume is mirrored on a horizontal axis.

### Actual Behavior

When clicking the "Flip Vertically" button in the paint editor, the costume is rotated 180°.

### Steps to Reproduce

See above

### Operating System and Browser

Windows 10 Home, Firefox 64.0

**Comment by joker314** [comment]
Thanks for letting us know! However, I'm **unable to reproduce** on Chrome, Windows 7 in Russian locale through beta.scratch.mit.edu.

Try these steps:
1. Open a new project
2. Navigate to the Scratch Cat's costumes and select the first one
3. Add a purple circle in the top-right of the cat
4. Select the 'Selection' tool again
5. Hit the 'Flip Vertically' button

Observe that the purple circle you drew appears in the bottom-**right**, not the bottom-**left**. This means it _is_ being mirrored rather than rotated. :slightly_smiling_face:

**Comment by gunchleoc** [comment]
I am skipping step 3 and 4 - see attached video

[Scratch-flip-vertically.zip](https://github.com/LLK/scratch-blocks/files/2719247/Scratch-flip-vertically.zip)

**Comment by thisandagain** [comment]
Moved to LLK/scratch-paint#810
