### ISSUE TITLE
Should we move cloud variables into an extension?

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-blocks#1889]
There has been discussion about moving cloud variables into an extension.

This would simplify the variable creation interface for most users, maintain functionality for users experienced with cloud variables, and increase visibility of the feature for users curious about trying additional features.

**Comment by towerofnix** [comment]
Another advantage to moving cloud variables into an extension would be having more leniency for adding blocks specific to cloud variables. This is a general advantage inherent to extensions; separating blocks into their own extensions means that users who add the extension will evidently be interested in exploring the blocks, and so will be more open to learning somewhat more advanced or specific use-case blocks. Since adding an extension is something users choose to do, they're much less likely to get overwhelmed like some were in 2.0, where obscure blocks like video sensing just felt noise.

Clearly you've already noticed this, @benjiwheeler, seeing #1890! There's also the possibility for blocks like "most recent user to change (cloud variable)" and "time when (cloud variable) changed" (although that latter one would take more consideration - what time format? - and is workaroundable with #1890).

**Comment by thisandagain** [comment]
Moved to LLK/scratch-gui#4488
