### ISSUE TITLE
Should we introduce a "when cloud variable updates/changes" hat block?

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-blocks#1890]
In discussions about cloud vars, users have expressed desire for an easier, more straightforward way to take action when a cloud var has changed.

This can be done using various patterns -- e.g., use a local variable to mirror the cloud variable, and have a forever loop check the cloud value against the local value.

But a "when cloud variable updates/changes" hat block would greatly simplify this.

Could be easier to do after/as part of moving cloud variables into an extension (see https://github.com/LLK/scratch-blocks/issues/1889 )

**Comment by towerofnix** [comment]
This reminds me of an extension I made a couple days ago:

![Three extension hat blocks: "when (Insert a block!) changes", "when (Insert a block!) becomes (Enter a value!)", "when <> becomes true"](https://user-images.githubusercontent.com/9948030/52281408-7cc78700-2934-11e9-99bd-45e8dec85ba9.png)

Thoughts on implementing an extension like that instead of this block? Obviously it would work nicely with cloud variable blocks, so I think it would be an interesting way to encourage users to mix and match extensions so that they work together.

(The overall benefits to my extension are that it's very generally useful, both practically and educationally; I just think it fits extra well with cloud variables as discussed here.)

**Comment by thisandagain** [comment]
Moved to LLK/scratch-gui#4489
