### ISSUE TITLE
Text to speech blocks are showing English names

### ISSUE THREAD

**Issue by gunchleoc** [LLK/scratch-blocks#1920]
The language names in the Text to Speech blocks are in English. I think we should use the native names instead, so children won't have to learn the English name for their language before they can use it. I think this is especially important for languages that don't use Latin script, like e.g. Japanese and Hindi.

**Comment by towerofnix** [comment]
The dropdown items are actually translated if your Scratch editor is in a different language - see this for example:

![The translate block in Chinese (I think), with the dropdown menu open; all options are the names of languages written in Chinese.](https://user-images.githubusercontent.com/9948030/55002309-23371c80-4fb5-11e9-9e1b-8edac0240e9e.png)

I think the reason they translate the languages to whatever the user's language is, is because then it's easier for the user to try translating it to languages they recognize the names of in the language that they speak.

**Comment by gunchleoc** [comment]
Yes, that would make sense too. How do I translate them? They are in English for Scottish Gaelic on https://llk.github.io/scratch-gui/develop/ and my translation is 100% completed and reviewed.

![text2speech-gd](https://user-images.githubusercontent.com/4095570/55018000-db7eb800-4fe9-11e9-9bec-9c68c944ec76.png)

We have language name translations available at the [CLDR](https://www.unicode.org/cldr/charts/latest/summary/gd.html).

I also just noticed that the "hello" string is missing translation markup too.

**Comment by benjiwheeler** [comment]
(one note: @towerofnix's screenshot was from the Translate extension; but @gunchleoc is talking about the Text to Speech extension)

The languages in the Text to Speech extension do seem to be translated, for most (maybe all?) languages now:

![image](https://user-images.githubusercontent.com/3431616/71302593-e6008f00-237a-11ea-9f95-93948127652e.png)

![image](https://user-images.githubusercontent.com/3431616/71302607-23fdb300-237b-11ea-84c9-81d87f0af961.png)

![image](https://user-images.githubusercontent.com/3431616/71302641-be5df680-237b-11ea-89a2-1de3c65637af.png)

I'm closing this as resolved, but please comment here if there's something I've missed!

**Comment by gunchleoc** [comment]
I can conform that the language names are translated. "hello" is still in English for https://llk.github.io/scratch-gui/develop/ but I only recently brought the translation back to 100% reviewed, so the translation might not have been pushed yet.
