### ISSUE TITLE
Implementation of basic multi-touch support

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#23]
@carljbowman and @tmickel experimented with multitouch a bit in the "Shakespeare" prototype. We need to spec our desired behavior / interaction.

Related to #24 #43

**Comment by tmickel** [comment]
I think we have most of the desired design resolved.

@rachel-fenichel 
- For our web implementation, just fix the implementation for now. Rachel has already made great progress on this, I think.
  - Second drag is ignored in general
  - Touching the workspace doesn't prevent you from dragging a block until the workspace is dragged (e.g., if you put your hand on the workspace and don't move it, you can still drag blocks).
- In the long run, we think it would be nice to have pinch-to-zoom (not dragging multiple blocks with multiple fingers). This is a general feeling of priority for using gestures for navigation over block manipulation (since it's really not necessary to manipulate multiple blocks at a time). Not sure if this is performant enough in the web implementation or not.

**Comment by thisandagain** [comment]
@tmickel @rachel-fenichel Should we close this and track any follow-up work in new tickets?

**Comment by tmickel** [comment]
Implemented!
