### ISSUE TITLE
text to speech extension not working in downloaded version of scratch

### ISSUE THREAD

**Issue by shivanik6z** [LLK/scratch-blocks#2510]
### Expected Behavior
It should have worked as it does on web version.

### Actual Behavior
When my program runs those extension blocks are not working!
![image](https://user-images.githubusercontent.com/31514274/122640643-4dd59880-d11e-11eb-855d-e2b3f5c19766.png)
when I click on the sprite, it does not work.

### Steps to Reproduce

Go to scratch windows download. Download it and do the same code as shown in the picture.

### Operating System and Browser

windows 10, chrome.

**Comment by apple502j** [comment]
Are you using the latest version (3.23.1) of Scratch Desktop?

**Comment by ericrosenbaum** [comment]
I'm not able to reproduce the problem with Scratch App 3.23.1 on Windows. 

If you don't have an internet connection, text to speech will not work (this is the expected behavior).

You network might be preventing it from working, for example due to limitations caused by a school network firewall (unfortunately we cannot do anything about this).

The only other thing I can think of is that your computer volume is turned off. 

Please check those things and let us know- thanks!

**Comment by BryceLTaylor** [comment]
I'm going to close as unable to reproduce. If you find more information about how to reproduce this, go ahead and open another issue.
