### ISSUE TITLE
Showing values associated with a block

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#254]
We need some way to draw values associated with a block. I believe these can be any string, and we don't need to support general HTML at this time (e.g. the way Snap does) - so we might want to draw it in the SVG rather than in an overlay (not sure though - might be easier with an overlay..)

<img width="162" alt="screen shot 2016-04-20 at 11 24 05 am" src="https://cloud.githubusercontent.com/assets/120403/14680213/85518502-06ea-11e6-9621-aa4f1073b9c8.png">

The bubble should wrap long values to a fixed width, and be able to display on the left as well as the right of the block.

I think this might be nice for vertical as well as horizontal eventually (if we add reporters to horizontal, for example).

@carljbowman

**Comment by tmickel** [comment]
Carl expressed some desire to have this thing animate. As in, move a little bit starting at the block. For this reason I think we should use an overlay, and possibly CSS transitions.

**Comment by tmickel** [comment]
Another thing I noticed about the Scratch 2.0 implementation: the bubble won't disappear as long as your mouse pointer continues to hover above the block. That seems like a nice feature to keep.

**Comment by towerofnix** [comment]
Should the content be cut off when it gets to be so tall (i.e. because of wrapping)? In Scratch 2.0 it isn't, making you get particularly long bubbles..

![Demo image](http://i.cubeupload.com/TYEdqS.png)

If so perhaps it should be scrollable? It's often useful to see all of the information, but you can't as Scratch 2.0 behaves (bottom gets cut off). It could be possible that the bubble stays relative to the block (right now it's an overlay on top of the entire editor) and you could scroll down the workspace to see the rest, but then you have to go away from the script you're currently editing, while just scrolling through the bubble itself would probably be easier.

**Comment by tmickel** [comment]
@liam4 That's interesting, thanks for sharing!

This does seem like an unfortunate edge case. A scrollable view or having it track to the block both seem like nice ideas. However I'm worried they might conflict with the fact that the bubble hides after some time (and after you move your mouse cursor away from the block) so it may actually be hard to get the behavior to be right. Maybe we could consider some mechanism for when values get extra long - e.g., if it's so big that it would be cut off the page, display the value in a scrollable pop-up modal dialog. Not sure what we want to do here, but it's good to keep it in mind. @carljbowman

**Comment by tmickel** [comment]
Moving to separate design issue, since a framework of implementation is done.
