### ISSUE TITLE
Remove Unused Features

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#316]
From #304:

> Might consider removing warning.js, mutator.js, icon.js, and all of their intermingled dependencies/usages - I think we will never want to use any of these, ever. Could consider removing bubble.js if we never want to use the current comment bubbles.

**Comment by carlosperate** [comment]
I would like to express my option about removing these features, since they are quite useful for applications that might have been using blockly and would like to move to scratch-blocks.

**Comment by thisandagain** [comment]
@carlosperate Thanks for the feedback. Which of these features are you using specifically?

**Comment by carlosperate** [comment]
Currently the warnings quite extensively. I was planning to use mutators in the future as well, which would require the icon to stay too.

**Comment by tmickel** [comment]
@carlosperate 
Is this the project you're working on: http://ardublockly.embeddedlog.com/ ?

We've done some stuff with Arduino as well (see: http://scratchx.org/#extensions) although within the framework of extending Scratch, rather than as a dedicated fork.

I could be argued into keeping warnings and icons as a feature, even if we don't use them in Scratch. We also usually find mutators as used in Blockly to be slightly unnecessary for Scratch (e.g. in the case of if-else, you can just combine multiple) or better served by configuration. What do you plan to use mutators for?

Of course, I'd expect we'll remain mostly-compatible with mutators and warnings even if we remove them, so you might not have that much trouble adding them back in.

**Comment by carlosperate** [comment]
Yes, that is the project I'm currently working on :) I saw the scratch x website when the scratch blocks were announced, but haven't had a chance to really check it out, the website doesn't respond to it when I click on the extensions.

About the mutators, I must admit I'm not a fan of the nested if statements, it would be something I'd definitely like to keep. It would also be needed for the function arguments as well. For personalised blocks, there was plans to use them for some blocks experimental blocks that configure certain things with pinouts, so you could include as many inputs as required.

**Comment by luxaritas** [comment]
Apologies for bumping what's more or less a zombie thread at this point, but I would also like to express my opinion on removing mutators specifically. I've been touching on readability in a couple places, and this is one important aspect. While personally the mutator interface isn't the best, the nested if blocks are definitely a huge readability problem I've seen with large projects (partially due to #457), and it can get out of hand quite quickly. Even if there isn't a switch capability (which would be nice), adding multiple "else if" conditions would at least come close (arguably, switch would be just slightly improved syntactic sugar, without needing to repeat the same condition). I could also seeing both of these implemented in the horizontal grammar something akin to the Mindstorms interface, with tabs: 
![ev3 switch](https://cloud.githubusercontent.com/assets/18635705/16433073/5a77b124-3d56-11e6-9cd8-90d35a8abfa9.png)

**Comment by thisandagain** [comment]
First pass of this is done and we went a little too far. Closing for now in favor of more specific bugs.
