### ISSUE TITLE
"Delete # Blocks" counts numbers as blocks in horizontal mode

### ISSUE THREAD

**Issue by Tymewalk** [LLK/scratch-blocks#342]
![](http://u.cubeupload.com/Tymewalk/extrablocks.png)
This was the only block I dragged out (I even refreshed the page and deleted all blocks). However, it still thinks there's an extra block there.

The problem is the number field as included in `blocks/math.js` is a separate block and counts towards the total.

The solution would be to check if the block being counted in the total is a number block or not:

```
// arbitrary pseudocode
if (block.Type != block.math.number) {
  // Only count non-number blocks
  blockCounter++;
}
```

**Comment by Tymewalk** [comment]
The code to count which blocks are deletable is here: [`core/workspace_svg.js:863`](https://github.com/LLK/scratch-blocks/blob/af963c9a0ed63a792fe189762a419c66fc01c485/core/workspace_svg.js#L863)

```
// Option to delete all blocks.
// Count the number of blocks that are deletable.
var deleteList = [];
function addDeletableBlocks(block) {
  if (block.isDeletable()) {
    deleteList = deleteList.concat(block.getDescendants());
  } else {
    var children = block.getChildren();
    for (var i = 0; i < children.length; i++) {
      addDeletableBlocks(children[i]);
    }
  }
}
```

We could sift through `block.getDescendants()` and then exclude any number blocks or related types.

**Comment by tmickel** [comment]
This is a great observation. I think it's the same problem we observed and fixed here:
https://github.com/LLK/scratch-blocks/issues/241

The context menu you're noticing - the one that pops up when you right click the workspace - must be counting blocks differently from the one that pops up when you right click a block.

The solution I think will be to not count the "shadow" blocks (context: https://groups.google.com/forum/#!topic/blockly/bXe4iEaVSao) which we are using in scratch-blocks for all of the fields/inputs. Rather than special-case for math.number, I think it's safe to never include shadow blocks in these numbers.

I'm going to close this issue and re-open the old one, just so we keep all the context in one place :)
