### ISSUE TITLE
Blocks cannot be created from flyout on dragging fields

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#357]
This applies to both horizontal and vertical. Not sure how this was introduced; it works fine upstream.

**Comment by rachel-fenichel** [comment]
Can you clarify?  I'm not sure what the title means.

**Comment by tmickel** [comment]
In the flyout, you can create a new block by clicking and dragging on the block. This also includes the part of the block that is the field - e.g., the fields/text boxes. When you click and drag on the fields in the flyout upstream, new blocks are created. In Scratch Blocks, nothing happens. I can make a video later :)

**Comment by drigz** [comment]
This is because they're shadow blocks, right? Upstream lets you grab flyout blocks by their fields, but not by their shadow blocks. If so, this is related to #277.

I put [this fix](https://github.com/drigz/scratch-blocks/commit/248134240a1e51e3f1ca9a4203fdeaed98cfd01c) together for both issues before I/O, but I think it belongs upstream.

**Comment by RoboErikG** [comment]
Yeah, this should be fixed in upstream. You can reproduce in the playground by trying to grab the edge of a shadow block in the toolbox.

**Comment by tmickel** [comment]
@RoboErikG @drigz Ah yes - thanks for pointing that out!

**Comment by tmickel** [comment]
I believe this is now fixed upstream (and in our merge). Thanks @drigz! :)
