### ISSUE TITLE
Displacing terminal statement blocks

### ISSUE THREAD

**Issue by NeilFraser** [LLK/scratch-blocks#397]
I'm looking at Blockly [Issue 414](https://github.com/google/blockly/issues/414).  Although that particular issue can be resolved by special casing shadow blocks, the root cause is a change in behaviour made to Blockly to match Scratch.  I'm questioning whether Scratch's behaviour is desirable.

Here is a movie showing Scratch's restricted options when dealing with terminal statement blocks.
  https://youtu.be/Qt33f_J6YxU
Note that this is inconsistent with all other block types, where one can displace an existing block by dragging in a replacement.

If a user drags a terminal statement block over another terminal statement block, it is clear what they want to do.  Can we remove the special exception we added that prevents the user from accomplishing their intended goal?

**Comment by tmickel** [comment]
@rachel-fenichel @ChampikaF @thisandagain @carljbowman Thoughts?

Here is our original discussion: https://github.com/LLK/scratch-blocks/issues/114

Here is another video, showing what I think the "intention" of the Scratch rule is:
https://www.dropbox.com/s/dgl3siyf59fdt39/no-next.mov?dl=0

I.e., it's not about dragging terminal statement blocks above other terminal statement blocks, but rather avoiding the "stack splitting" behavior which happens when connecting a terminal statement block in the middle of the stack.

Notably, what happens if we change the rule and keep insertion markers? Do the blocks "temporarily split" to show the insertion marker in the middle of the stack, and then "re-join" when you drag away from the stack?

**Comment by NeilFraser** [comment]
I remember the original discussion and at the time I thought terminal statement blocks were rare enough that what we did probably didn't really matter.  But as a result of the change I'm seeing increased issues.  Such as kids getting frustrated with the Bird in Blockly Games where the heading blocks are no longer easily swappable:

![heading](https://cloud.githubusercontent.com/assets/250480/15988794/50097f70-3012-11e6-9970-c7b8c35fcd09.png)

For reference, Scratch does allow the equivalent behaviour on horizontal blocks:

![value](https://cloud.githubusercontent.com/assets/250480/15988826/a36525ec-3013-11e6-8d17-6e9a451d65ee.png)

**Comment by tmickel** [comment]
Sorry to hear about the frustrations :(

I still don't have a good idea about how we could possibly do this in a nice way while keeping insertion markers. That is also the case for inputs - we still need to design what to do with those, as bumping the blocks in inputs out of place "temporarily" during a drag would probably be a surprising behavior.

Maybe this is another area where Blockly's default behavior should diverge from scratch-blocks? Since Blockly doesn't have insertion markers right now, it seems like there are not necessarily the same issues.

**Comment by NeilFraser** [comment]
Let's figure out what we want to do regarding insertion markers for value blocks.  I'd rather have a consistent UX, than a collection of evolved behaviours.  Less code, greater reliability, fewer surprises.

**Comment by rachel-fenichel** [comment]
> Notably, what happens if we change the rule and keep insertion markers? Do the blocks "temporarily split" to show the insertion marker in the middle of the stack, and then "re-join" when you drag away from the stack?

Yes, can do.

> That is also the case for inputs - we still need to design what to do with those, as bumping the blocks in inputs out of place "temporarily" during a drag would probably be a surprising behavior.

Yeah this seems like keeping the highlight is probably more desirable.

> Since Blockly doesn't have insertion markers right now, it seems like there are not necessarily the same issues.

It's definitely a goal though.

**Comment by rachel-fenichel** [comment]
I think Neil's use case--replacing one terminal block with another terminal block--is worth supporting.  In both that case and the dragging-toward-occupied-input case, bumping the block away would be weird.  I propose that we keep the scratch behaviour for the inputs: dragging a block over an occupied input highlights the entire block in the input/the entire input, showing that it will be replaced.  Similarly, we can do a white glow around the existing terminal block to indicate that it will be replaced by the dragged block. 

In the case of a shadow the existing block will disappear; in the case of a concrete block it will disconnect and bump away.
