### ISSUE TITLE
Predicates and string reporters can't be placed in number inputs

### ISSUE THREAD

**Issue by jeandrek** [LLK/scratch-blocks#410]
If I try to drag a predicate block or a reporter that reports a string into a number input, it just jumps back.

**Comment by tmickel** [comment]
Thanks for raising this. In order to get this right, I think we have to do some refactoring of render code to separate type-checking from reporter-shaping. We're also still considering some things - like whether string reporters should have squared-off edges or not - and we'll probably wait to fix this until we resolve a final design for shape, color, and compatibility of all types of inputs @carljbowman.

**Comment by rachel-fenichel** [comment]
Out of curiosity, what's the use case for dragging a string into a number input?

**Comment by tmickel** [comment]
This is a contrived example and I'm sure there are many better ones, but:
<img width="211" alt="screen shot 2016-06-15 at 3 55 42 pm" src="https://cloud.githubusercontent.com/assets/120403/16095207/a4a47394-3311-11e6-8a05-b1deeaf92556.png">

**Comment by rachel-fenichel** [comment]
Yup, the reporter that reports a string makes perfect sense, given scratch's type system.  It's the other case I'm thinking about.

**Comment by rachel-fenichel** [comment]
Meant to ask: when would you drag a predicate block into a number input.

**Comment by tmickel** [comment]
another contrived example :)
<img width="331" alt="screen shot 2016-06-15 at 5 20 16 pm" src="https://cloud.githubusercontent.com/assets/120403/16097740/737a7f82-331d-11e6-8d67-73d67fb8029e.png">

**Comment by ghost** [comment]
Oh, and these conditional operators have been appearing a lot too.
![scratchblocks 1](https://cloud.githubusercontent.com/assets/6393827/16123244/84a1e7ca-33a7-11e6-8c86-551da7c87b8f.png)

**Comment by tmickel** [comment]
I believe this has been fixed :)
