### ISSUE TITLE
Duplicating a block does not attach it to the mouse pointer

### ISSUE THREAD

**Issue by NoMod-Programming** [LLK/scratch-blocks#411]
This is the default behavior in scratch 1.4 & 2.0, and makes it much easier to program, especially with large scripts, as the position of the duplicated blocks can get confusing to some users.

**Comment by tmickel** [comment]
@rachel-fenichel This seems like it would require a little bit of refactoring of how drags work, maybe. Any thoughts?

**Comment by towerofnix** [comment]
Just dispatch the `dragstart` event on the new duplicated block? (Assuming HTML5 drag and drop.)

**Comment by rachel-fenichel** [comment]
Is the only way to duplicate a block through the right click menu?

**Comment by towerofnix** [comment]
In Scratch 2.0 you can also use the duplicate tool, it looks like a stamper in the toolbar.

**Comment by rachel-fenichel** [comment]
@liam4: thanks for the fast response!  Is there any way to duplicate a block mid-drag?  For instance, Blockly has keyboard shortcuts for this as well.

**Comment by sbgp-review** [comment]
We'll also need to consider how this works on tablets where there is no
cursor.

On Wed, Jun 15, 2016 at 12:46 PM, rachel-fenichel notifications@github.com
wrote:

> @liam4 https://github.com/liam4: thanks for the fast response! Is there
> any way to duplicate a block mid-drag? For instance, Blockly has keyboard
> shortcuts for this as well.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/LLK/scratch-blocks/issues/411#issuecomment-226298743,
> or mute the thread
> https://github.com/notifications/unsubscribe/ARD-VvItx4hjD7qe2qnfd8wz29sPCz_Xks5qMFaNgaJpZM4I2AKQ
> .

## 

Erik Pasternak | Master of the House | epastern@google.com

**Comment by towerofnix** [comment]
Just happened to post our posts at the same time :)

In the paint editors you can hold down shift when using the duplicate tool to make it so that after you've placed down a shape it'll still have the same shape in its hand (a copy). It doesn't look like the same functionality works for blocks (or sprites, for that matter).

**Comment by NoMod-Programming** [comment]
@sbgp-review It seems that there might need to be different behavior depending on the type of grammar used. In vertical grammar, it would make sense to attach the block to the mouse pointer when it is duplicated, and this is the case in earlier versions of scratch. However, in horizontal grammar, because the blocks are smaller, and because it is geared towards a touchscreen, it would make more sense to just have the block placed like it currently is.

**Comment by rachel-fenichel** [comment]
Scratch 2.0 behaviour: if you use the duplicate tool it creates a new block slightly down and to the right of the old block.  It does not attach to the mouse pointer for a drag.

If you right click on a block and click "duplicate", it will duplicate and attach to the mouse pointer.  It will follow the mouse pointer until you click again.

This is interesting because you don't have to have the mouse clicked at all times during a drag.  That is, drags always happen with a sequence of mouseDown (pickup), mouseMove, mouseMove, mouseMove, mouseUp (drop).

To have the scratch behaviour we need the drag to be mouseMove, mouseMove, mouseDown (drop), mouseUp (do nothing).

Still looking into how hard this is.

**Comment by tmickel** [comment]
@rachel-fenichel If you happen to touch this code when doing the mouse/touch refactors, might be worth considering :)
