### ISSUE TITLE
Bumping moves the stack where a block is inserted

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#418]
<img width="397" alt="screen shot 2016-06-15 at 5 46 49 pm" src="https://cloud.githubusercontent.com/assets/120403/16098485/32ee5520-3321-11e6-9f68-77895aabcff2.png">

In this example, if I take the right "and" block and insert it on top of the one in the stack on the left, the left one gets bumped out. The block is replaced out of the stack appropriately. But, the entire left stack jumps a little to the right and to the bottom. Is this intentional?

**Comment by rachel-fenichel** [comment]
Not intentional, and it's pretty disruptive.

**Comment by tmickel** [comment]
fwiw, something similar seems to happen upstream:
![bumping-weird](https://cloud.githubusercontent.com/assets/120403/16134053/2abae2ba-33e9-11e6-8d5f-c847c7d6f668.gif)

**Comment by rachel-fenichel** [comment]
What's happening here is that the first input of the bumped block (call that block B) is close enough to the output of the outer block (call that block A) that a connection is possible.
![image](https://cloud.githubusercontent.com/assets/13686399/16636812/4666b218-438f-11e6-9937-8e9dc97971f8.png)

(The highlighted block just got disconnected and is on top of another block)
As a result, something needs to bump.  It's going to be block A because the relevant connection is an output, which is an inferior connection type.

After the first bump, it looks like this:
![image](https://cloud.githubusercontent.com/assets/13686399/16636777/193276e2-438f-11e6-9fa5-ac1002b7c140.png)

Then the output of B is close to the input of A, so B bumps as well.
![image](https://cloud.githubusercontent.com/assets/13686399/16636796/3342f2a0-438f-11e6-8f60-fa206c8e3d96.png)

One solution might be to prioritize connections on the parent block in the bump, regardless of whether they are superior or inferior in the connection typing hierarchy.
