### ISSUE TITLE
Blockly.BUMP_DELAY

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#424]
What is the idea of this delay? Can we take it out?

Right now, it makes bumps wait 250ms before they are visible. Makes it feel like there's a "slowness" to me.

**Comment by RoboErikG** [comment]
Sorry I missed this earlier. This just came up in a meeting today, Neil added it because users were sometimes confused by the bump when it didn't seem to be caused by their action or they missed it because it happened while other things were moving. The delay is to make it easier for users to see the bump and understand why it happened.

A better version would probably be a short animation of the block bumping away.

**Comment by tmickel** [comment]
Ok, we'll discuss around here :)

**Comment by tmickel** [comment]
Thanks for the background!

**Comment by tmickel** [comment]
We discussed, and decided to just set to 0 and set it back if we notice the same confusion in tests. Thanks again for the explanation :)
