### ISSUE TITLE
Specialized Menu — Color Picker

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-blocks#460]
Breaking out from [Design - Specialized field editors - Issue #149](https://github.com/LLK/scratch-blocks/issues/149)

For example, this will be used in places like 'color touching [  ] ?'
<img width="327" alt="screen shot 2016-06-29 at 9 26 51 am" src="https://cloud.githubusercontent.com/assets/3409578/16453666/aa807b3a-3ddb-11e6-9455-56e2666db3d6.png">

**Comment by tmickel** [comment]
Note for this one:

A consideration that seems important to me is picking colors from the stage. This makes things like "touching color" much easier, because you can pick out the exact color from a sprite. Unfortunately, technical limitations mean we can't do "pick any color from the screen" like we do in scratch-flash. One option may be to jump the mouse to the stage during a color pick (colors can definitely be picked from the stage) and change the cursor to a "color picker." Of course, this wouldn't work so well with touch. Another feasible option would be to take a screenshot of the stage when the color picker is opened, and include that along with a standard spectrum (perhaps in a separate tab, perhaps not).

**Comment by towerofnix** [comment]
Would something like this work well?

![Demo](https://cloud.githubusercontent.com/assets/9948030/16468015/5f9f44f8-3e20-11e6-8b99-bbe74f582661.png)

When you click on "grab from stage" the normal color picker is replaced with a picture of the stage. The button would probably be replaced with "use color picker" as well.

It might be good if there were a "snapshot" button that would take a picture of the stage as it is at the time the button's pressed, with the "grab from stage" button instead of replacing the color picker with a _picture_ of the stage, replace it with a _live video_ of the stage.

**Comment by NoMod-Programming** [comment]
@liam4 I think it would be easier if any color were able to be grabbed from anywhere on the screen, similar to 1.4. That would allow for picking colors from more than the stage (maybe rename "Grab from Stage" to "Grab from screen")

**Comment by cpseager** [comment]
Would be great to include a 'zoomed' area to be able to pick a particular pixel colour much easier, particularly when using touch e.g. a zoom area like shown here:

http://html-color-codes.info/colors-from-image/

**Comment by PullJosh** [comment]
Is it possible to allow users to pick a color from anywhere on the screen? I don't remember exactly how it's done, but I'm pretty sure it's possible to "screenshot" the page and then put it on an off-screen canvas to then be able to pick the colors out of that canvas based on cursor location. It would be a bit of extra work, but I think it's a feature worth having. (Make sure a color palette appears on-screen as well, so we can pick from that!)

**Comment by mrjacobbloom** [comment]
@PullJosh there's a way to insert an HTML page into an SVG and render that SVG in the canvas but it's limited and I feel like it's pretty labor-intensive. Might be a lot of work just for the color menu

**Comment by tmickel** [comment]
Current/Blockly implementation:
<img width="204" alt="screen shot 2016-07-14 at 4 20 18 pm" src="https://cloud.githubusercontent.com/assets/120403/16854443/e71b4494-49de-11e6-8b5d-f505c34b12a4.png">

**Comment by TheBrokenRail** [comment]
Here's some code that will render DOM objects in a canvas.
```js
var canvas = document.createElement('CANVAS');
canvas.width = "200";
canvas.height = "200";
var ctx = canvas.getContext('2d');
var html = "Put HTML Here";
var data = '<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200"><foreignObject width="100%" height="100%"><div xmlns="http://www.w3.org/1999/xhtml">' + html + '</div></foreignObject></svg>';

var DOMURL = window.URL || window.webkitURL || window;

var img = new Image();
var svg = new Blob([data], {type: 'image/svg+xml'});
var url = DOMURL.createObjectURL(svg);

img.onload = function () {
  ctx.drawImage(img, 0, 0);
  DOMURL.revokeObjectURL(url);
}

img.src = url;
document.children[0].appendChild(canvas);
```

**Comment by paulkaplan** [comment]
So let's use this issue just to track the actual color editor, the eyedropper part of this will be handled by the GUI. We'll need hooks to activate it from scratch-blocks, but I'm tracking that here: https://github.com/LLK/scratch-blocks/issues/1057
