### ISSUE TITLE
Toolbox - Support Scratch Jr style

### ISSUE THREAD

**Issue by RoboErikG** [LLK/scratch-blocks#5]
- [x] Allow Toolbox to be placed at different locations.
- [x] Allow Toolbox to support horizontal layout of blocks and labels.
- [ ] Make sure Toolbox labels can support icons.
  - [x] Allow icons instead of text labels.
  - [ ] Ensure alt text for icons works.
  - [ ] Support selection UI for icons.

**Comment by SCrolem** [comment]
Hi , i got a serious problem trying to put this working (the part of icons instead of text) :(, can someone say me if this is outdated and dont work anymore or what should i do to make this working? i just wanted too change categories text to icons but for some reason i can´t put it working.  thanks
