### ISSUE TITLE
Design for "create variable" button and dialog

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#535]
Placeholders right now:

![image](https://cloud.githubusercontent.com/assets/13686399/16853924/79b4bfae-49c3-11e6-95d0-f44eadb45a47.png)

![image](https://cloud.githubusercontent.com/assets/13686399/16853949/9f7c6606-49c3-11e6-9dd6-73d1fb73c0d0.png)

**Comment by carljbowman** [comment]
Todo - 
- [ ] Document 2.0 Variable Deletion Behavior
- [ ] Document 2.0 Variable Editing/Renaming Behavior
- [ ] Document 2.0 Dragging Variables to Sprites/Stage Behavior

# Scratch 2.0 - Creating a Variable Behaviors

## Clicking 'Create a Variable' opens dialog
![open-dialog mov](https://cloud.githubusercontent.com/assets/3409578/23029551/f1297550-f438-11e6-8187-9e481ce1b063.gif)

## Ability to Name a Variable
![name-var mov](https://cloud.githubusercontent.com/assets/3409578/23029651/42f14e44-f439-11e6-9a6c-c8375be6b4cf.gif)
- Variables cannot have the same name (case sensitive), if the user tries to name a Variable with the same name an error will be thrown
![name error mov](https://cloud.githubusercontent.com/assets/3409578/23031038/98a545b2-f43d-11e6-8f0c-82b324115bc4.gif)
![screen shot 2017-02-16 at 11 47 23 am](https://cloud.githubusercontent.com/assets/3409578/23031063/b15c3d4a-f43d-11e6-9378-d84f793f73e5.png)
- A user can create two 'For this sprite only' variables that have same name across two different sprites

## Ability to Choose if the Variable is 'For all sprites' or 'For this sprite only'
![var global or local mov](https://cloud.githubusercontent.com/assets/3409578/23029868/e60d2be8-f439-11e6-8c52-c64489277991.gif)

- **For all sprites (aka Global):** The Variable that is created will be accessible in the 'Data' category on all sprites
![global var mov](https://cloud.githubusercontent.com/assets/3409578/23030254/3a28ccea-f43b-11e6-9dc0-a34091e27282.gif)

- **For only this sprite (aka Local):** The Variable that is created will only be accessible in the 'Data' category on the sprite it was created. (Unless manually dragged to another block)
![local var mov](https://cloud.githubusercontent.com/assets/3409578/23030622/478a360c-f43c-11e6-9814-05aa3d8abd4d.gif)

## Cloud Var checkbox 
**This will only appear for users who have been given access to the Cloud Variable feature and can only be checked 'On' for 'For all sprites' variables**
![toggle cloud var mov](https://cloud.githubusercontent.com/assets/3409578/23030601/3a233342-f43c-11e6-9652-b028e2bf9f91.gif)

**Comment by carljbowman** [comment]
Todo:
- [ ] Spec 3.0 Variable Deletion Behavior
- [ ] Spec 3.0 Variable Editing/Renaming Behavior
- [ ] Spec 3.0 Dragging Variables to Sprites/Stage Behavior

# Scratch 3.0 - Round 1 - Creating a Variable Behaviors
Overall we should the keep current behavior within Scratch 2.0 that is outlined above. 

**Cloud Vars are out of scope for this initial pass. The sketches include the option to explore the extensibility of the dialog component**

## Opening 'Make a Variable' Dialog
User Clicks 'Make a Variable' button
![r1 5 2_gui_make-a-var_step_1](https://cloud.githubusercontent.com/assets/3409578/23215085/1c3c440c-f8df-11e6-8e95-7276646a2d65.png)

Dialog opens
![r1 5 2_gui_make-a-var_step_2](https://cloud.githubusercontent.com/assets/3409578/23215090/1e704df4-f8df-11e6-9a38-e5c98efe0f3c.png)

## Close 'Make a Variable' Dialog

- User can click the transparent background 
- User can click the ( x ) icon in the upper right corner
- User can click the 'Cancel' button

![r1 5 2_gui_make-a-var_step_3](https://cloud.githubusercontent.com/assets/3409578/23215291/d45bc832-f8df-11e6-9510-a3f8b4713c63.png)

## Naming a Variable
- User can name the variable
![r1 5 2_gui_make-a-var_step_4](https://cloud.githubusercontent.com/assets/3409578/23215404/40734f9a-f8e0-11e6-854b-25dff36cb723.png)

- Variables cannot have the same name (case sensitive), if the user tries to name a Variable with the same name an error will be thrown
@rschamp - Might be nice to utilize some of the validation mechanisms we built in the Join Flow, rather than popping another dialog like in 2.0. Not 100% sure about this idea as this feels like an error state, which we have traditionally avoided. Needs discussion.
![r1 5 2_gui_make-a-var_step_5](https://cloud.githubusercontent.com/assets/3409578/23216133/e27053b8-f8e2-11e6-9436-4a653cdcb698.png)

- A user can create two 'For this sprite only' variables that have same name across two different sprites

## Ability to Choose if the Variable is 'For all sprites' or 'For this sprite only'
- User can toggle these options
- Another place we could leverage some of the UI (checkboxes, radio button) from the Teacher Join flow on WWW

![r1 5 2_gui_make-a-var_step_6](https://cloud.githubusercontent.com/assets/3409578/23216455/04d67a8a-f8e4-11e6-95a2-13e20e66b30d.png)

- These options should follow the 2.0 model (see https://github.com/LLK/scratch-blocks/issues/535#issuecomment-280390616 for more info):
  - **For all sprites (aka Global):** The Variable that is created will be accessible in the 'Data' category on all sprites
  - **For only this sprite (aka Local):** The Variable that is created will only be accessible in the 'Data' category on the sprite it was created on. (Unless manually dragged to another block)

## Cloud Var checkbox
**This will only appear for users who have been given access to the Cloud Variable feature and can only be checked 'On' for 'For all sprites' variables**

- User with access to Cloud Vars
![r1 5 2_gui_make-a-var_step_7](https://cloud.githubusercontent.com/assets/3409578/23216756/21760e2a-f8e5-11e6-9539-a7a0d2aaaca2.png)

- User without access to Cloud Vars
![r1 5 2_gui_make-a-var_step_8](https://cloud.githubusercontent.com/assets/3409578/23216879/79caa3ec-f8e5-11e6-852e-8d39c315bcd6.png)

## Variable Created
- Single Variable
![r1 5 2_gui_make-a-var_step_9](https://cloud.githubusercontent.com/assets/3409578/23216993/d2cca1fc-f8e5-11e6-9ebe-64ec24c93be3.png)

- Multiple Variables
![r1 5 2_gui_make-a-var_step_10](https://cloud.githubusercontent.com/assets/3409578/23217120/374f45d0-f8e6-11e6-83ce-6d7e6f16034f.png)

## Proportions
We will need to refine these over time as we create more dialogs, but these will work for now.
![r1 5 2_gui_make-a-var_step_11](https://cloud.githubusercontent.com/assets/3409578/23217353/eb3da848-f8e6-11e6-85e1-26cf542e0f11.png)

Orange: 0.75 rem (12px)
Green: 1.5rem (24px)
Purple: 2.25rem (36px)

**Comment by thisandagain** [comment]
Done enough to move forward with.

**Comment by thisandagain** [comment]
For playtest don't worry about the variable scope or cloud variables. We will get to that in a future iteration.
