### ISSUE TITLE
field_dropdown focus override by value report

### ISSUE THREAD

**Issue by xmeow** [LLK/scratch-blocks#566]
I can't pop the dropdown menu because the workspace.reportValue take over the focus.
![image](https://cloud.githubusercontent.com/assets/3390845/17642050/d63d1df2-616a-11e6-82fa-7a16c7993344.png)

It works fine if I block the promise callback..
![image](https://cloud.githubusercontent.com/assets/3390845/17642058/13c9ab72-616b-11e6-8b4e-95abddf2985e.png)

Is there any way not to execute the block if click on field_dropdown?

**Comment by tmickel** [comment]
Hi @xmeow!

Yes, that's very annoying...

We're tracking it here:
https://github.com/LLK/scratch-blocks/issues/307
and here:
https://github.com/google/blockly/issues/336

Hopefully should get a fix sooner rather than later, as it's starting to interfere with our prototyping for Scratch, too. Thanks for the report!

P.S. - not sure what you're building, but just an advisory that this codebase is still in its early stages, and things might change a lot in the coming months!
