### ISSUE TITLE
Variables - Getter block to match Scratch 2.0

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#573]
This block should have a single text field, set to the name of the variable, but the right-click menu should behave like the dropdown on a fieldVariable.

**Comment by MegaApuTurkUltra** [comment]
Please don't make us have to keep using `([] of [])` for getting variables by name!

https://scratch.mit.edu/discuss/topic/211154/

**Comment by towerofnix** [comment]
Though to really make it work well you could add a label "variable with name", or something.

**Comment by TheBrokenRail** [comment]
I prefer the current system it makes it easier to delete, rename, and change the variable in the reporter

**Comment by TheBrokenRail** [comment]
I also like the dynamicly get variable thing. PLEASE do not change it to 2.0-style

**Comment by CatsAreFluffy** [comment]
Maybe have both? The current system for those particular cases and 2.0's for convenience. It would also be good if you could switch between them in the right-click menu.

**Comment by towerofnix** [comment]
IMO an "of myself" block would fit best with 2.0, as it is now.

**Comment by mrjacobbloom** [comment]
I feel like the option to switch between them would be messy and unnecessary. +1 for "myself" or "this sprite" option in the "_ of _" sensing block

**Comment by TheBrokenRail** [comment]
I like the dropdown version because currently you can create semi-hacky dynamic variables with but without actually hacking the blocks because you can drop a reporter into the variable getter, and setter, if variables are designed like 2.0, you would have to hack the xml of the sensing of block because you cannot put reporters into sensing of.

**Comment by towerofnix** [comment]
Yeah, but it doesn't *look* good:

<img width="157" src="https://cloud.githubusercontent.com/assets/9948030/21725600/758168d4-d40f-11e6-9f0f-62893b0f3f0e.png">

The only visible thing that tells you it's a dynamic variable getter is the red ring around the block. That's not very obvious, which is why I suggested `(var name) of [myself]`.

**Comment by carljbowman** [comment]
@rachel-fenichel - As we discussed we should update the variable getter to match 2.0. As you described the menu items should appear in the right-click. 

<img width="238" alt="screen shot 2017-01-17 at 9 52 24 am" src="https://cloud.githubusercontent.com/assets/3409578/22025170/ae34203e-dc9a-11e6-8ad3-1cfc6167e356.png">

**Comment by CatsAreFluffy** [comment]
Typing in the variable name should still be an option. It can get
inconvenient when you have 500 variables in your project.

**Comment by CatsAreFluffy** [comment]
RIP fun times
