### ISSUE TITLE
Implement custom procedures

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [LLK/scratch-blocks#607]
Lots of people's 2.0 custom blocks won't make any sense when converted into the new format.

For example this:

![](http://i.imgur.com/MLZY32w.png)

Would presumably become something like this in the conversion from 2.0 to 3 format

![](http://i.imgur.com/NiRO0vh.png)

Scratchers might get confused by things like this.

**Comment by tmickel** [comment]
The current implementation is a direct copy-paste from Blockly - the actual version is only in the earliest design stages, and is likely to look significantly different. @carljbowman

**Comment by tmickel** [comment]
From @TheBrokenRail:

> Here's Some Issues I Found With The UI in procedure blocks/custom blocks
> - [ ] Need Space Between Blocks In Block Palate
> - [ ] Input Block Is Offset From Curser
> - [ ] No Background For Warning About Standalone report block Needing To Be Used In a custom block definition
> - [ ] Needs Proper UI for input Selection
> - [ ] Gear And Warning Triangles should be maybe should be the same color as the blocks
> - [ ] Use Define Instead of to
> - [x] Bottom of define with report is longer than top

**Comment by rachel-fenichel** [comment]
One more:
- Need to be able to add label text between inputs

**Comment by tmickel** [comment]
Yep, and inputs need types (number, string, boolean).

**Comment by towerofnix** [comment]
Don't forget default values for number/string inputs! That's implemented in the actual "blocks" part of Scratch 2.0 (though there's no UI for it atm).

**Comment by CosmicWebServices** [comment]
Moved from #631:

![image](https://cloud.githubusercontent.com/assets/10731781/18887337/9df51f9c-84c1-11e6-9eb6-d884cac3ffbe.png)

The define part is hard to read because of the color of the text.

**Comment by towerofnix** [comment]
Also the red outline is _really_ red. It's kind of hard to see. Later on the shape will probably be changed to look like a stack (or reporter) outline but for now the color should probably be fixed anyways.

Reasons for the same color as the outline of stack blocks:
- It _is_ the outline of a block.
- It represents a block more clearly.

Reasons for a lighter or different color:
- It's actually the outline of a preview of what the block will look like, generally, so it distinguishes between a real block and a preview.
- It looks similar to how custom block definitions currently look.

Also probably more but just some observations. :)

**Comment by TheBrokenRail** [comment]
When selecting the name field it gets all big and weird and when closing even bigger fort a moment, can you change it to be like other text fields?

**Comment by tmickel** [comment]
@TheBrokenRail I believe that's actually an unrelated bug with text fields not in shadow blocks. If you'd like that could be filed and fixed separately!

**Comment by tmickel** [comment]
@dekrain points out we need to generate shadow blocks:
![pseudo-fields](https://cloud.githubusercontent.com/assets/19158291/19125062/f11e2838-8b35-11e6-9a20-d5f3a7f10e6f.png)
https://github.com/LLK/scratch-blocks/issues/665

**Comment by TheBrokenRail** [comment]
We need padding between the define and report blocks in the block palate

**Comment by mrjacobbloom** [comment]
For custom reporter definitions, I like the idea of dragging the standalone "report" block out from the bottom of the c-block to copy it, just like we do with procedures' arguments in 2.0

**Comment by TheBrokenRail** [comment]
Why were custom reporters removed?

**Comment by dekrain** [comment]
Why were toolbox removed

**Comment by TheBrokenRail** [comment]
With The New Changes We should also a "create procedure dialog"

**Comment by tmickel** [comment]
@dekrain The toolbox is not removed.
@TheBrokenRail We never implemented custom reporters in the first place. What was there before was a copy from Blockly.

**Comment by TheBrokenRail** [comment]
I was really hoping for custom reporters, it would have been a great feature.

**Comment by tmickel** [comment]
@TheBrokenRail Whether we have this feature is independent of whether it currently exists in the scratch-blocks code. We have a lot of work to do to support custom blocks.

**Comment by rachel-fenichel** [comment]
Model (not view) questions:
-- Who keeps the master list of procedures?  I assume it'll be the VM
-- How does the VM tell blockly about the list of procedures?
-- Does that information need to be passed back and forth at any time other than when opening the "More Blocks" section of the toolbox?
---- If it's only at that one point, does Blockly need an explicit list of procedures, or can we get away with just replacing procedures.js:flyoutCategory()?
-- What is the unique identifier for a procedure?
---- Will you allow multiple procedures with the same name + same named arguments in Scratch 3.0?  _Scratch 2.0 allows this, but I consider it a bug.  It means that the definition of your procedure at runtime depends on which block you least recently interacted with._ 
-- How will you handle multiple procedures with the same name + arguments that are implemented differently in different workspaces?
-- Will it be possible to define procedures for the whole project, or only for individual sprites?
-- What happens if you drag a procedure call from one sprite to another sprite?

**Comment by tmickel** [comment]
@thisandagain @cwillisf Assigning for feedback on Rachel's questions above

**Comment by cwillisf** [comment]
> Will you allow multiple procedures with the same name + same named arguments in Scratch 3.0? _Scratch 2.0 allows this, but I consider it a bug. It means that the definition of your procedure at runtime depends on which block you least recently interacted with._

I also consider this a bug. I suggest that if two procedures "become" identical then we add a disambiguating suffix to the name of the one that caused the ambiguity, just like we do with sprites and costumes and such. That is, `foo` becomes `foo2` upon collision.

If we end up in a situation where there's ambiguity, for example if someone hand-edits their project files to see what happens, then I think any result other than crashing / throwing is fine. IMO predictable-but-strange behavior, like that of Scratch 2.0, is almost a bonus in this situation since it likely means we have a tinkerer and they might enjoy puzzling it out to glean insight into our implementation.

"Any result other than crashing / throwing" includes, for example, if `scratch-blocks` decides to show only one instance of the procedure in the palette despite there being two definitions in the workspace. I would prefer to preserve the two definitions' bodies, if that's feasible. The VM can do whatever is convenient with the duplicate definition, such as (effectively) throwing / overwriting one with the other.

> Will it be possible to define procedures for the whole project, or only for individual sprites?

We've talked about this occasionally on the Scratch team but haven't settled on a good way to present it to the user. If there's a reasonable way to leave room for this as a possibility I think that would be a good idea, but I don't believe it's in the plans at the moment.

> What happens if you drag a procedure call from one sprite to another sprite?

I'm in favor of the current Scratch 2.0 behavior where the block is copied to the destination sprite but doesn't do anything meaningful there unless a matching procedure exists there. This makes it easier to copy a big block of code and then adjust it after the copy. Maybe we'd want to show that the call is in an error state somehow, but I think that's a nice-to-have.

> How will you handle multiple procedures with the same name + arguments that are implemented differently in different workspaces?

I think this is OK to leave in the hands of the VM: the VM knows which sprite a block is running against and can look up the right procedure using that knowledge. On the VM side, I'm sure procedures' info will be stored in such a way that they're associated with a particular context. We'll just need to know the name and argument types that the block believes it should be calling, and the VM will be responsible for looking up the right procedure from there. If that information is encoded into a single ID-like value ([C++ name mangling](https://en.wikipedia.org/wiki/Name_mangling#C.2B.2B), anyone?) then that might improve performance of procedure-heavy projects. On the other hand, I don't believe procedure lookup is a common bottleneck so I don't think that finding such an encoding is strictly necessary.

(That's not to say that there are no projects for which procedure lookup is a bottleneck. I've accepted a few PRs in `scratch-flash` from some of our power-users where they claimed to see significant performance gains by optimizing procedure lookup...)

**Comment by luxaritas** [comment]
> > Will it be possible to define procedures for the whole project, or only for individual sprites?
> 
> We've talked about this occasionally on the Scratch team but haven't settled on a good way to present it to the user. If there's a reasonable way to leave room for this as a possibility I think that would be a good idea, but I don't believe it's in the plans at the moment.

Out of curiosity, why is procedures available for all sprites any less clear than variables for all sprites? I understand the clarity issue, but isn't that just as much of an issue with global variables? Is it specifically the location of the definition?

**Comment by mrjacobbloom** [comment]
If we treat global procedures like we do global variables then I can see possible compatability issues with 2.0. If procedures in the stage automatically become global then there could be name collision issues

**Comment by luxaritas** [comment]
Why would we need to be concerned about compatibility going from 3.0 to 2.0? I don't think you could load 2.0 projects into 1.4, could you?

**Comment by ghost** [comment]
@LFP6 The compatibility issue is from 2.0 to 3.0, when there's custom blocks of the same name in the Stage and another sprite.

**Comment by dekrain** [comment]
Now I know what is wrong! In https://github.com/LLK/scratch-blocks/blob/develop/blocks_vertical/procedures.js#L57 it should be
```JavaScript
container.setAttribute(name, value);
```
instead of
```JavaScript
var el = document.createElement(name)
el.setAttribute('value', value);
container.appendChild(el);
```
or in `domToMutation`.

**Comment by thisandagain** [comment]
@carljbowman Note for default "input" label from discussion with @ntlrsk:
Pico Cricket used `box1`, `box2`, etc. rather than "input" or "thing" which worked well.

**Comment by carljbowman** [comment]
Todo
- [ ] Document 2.0 Using Custom Procedures
- [ ] Document 2.0 Dragging Custom Procedures to other Sprites
- [ ] Document 2.0 Dragging Custom Procedures to the Backpack

# Scratch 2.0 - Create a Custom Procedure Behaviors

## Clicking 'Make a Block' opens Dialog
![make block dialog mov](https://cloud.githubusercontent.com/assets/3409578/23038504/4297fe24-f458-11e6-8eb5-b144e101e800.gif)

## 'Naming' block
![name-block mov](https://cloud.githubusercontent.com/assets/3409578/23038591/9268a2b4-f458-11e6-801e-8c412e95cd18.gif)

As @cwillisf mentioned there is no unique identifier that is displayed to the user. For example, in the image below, there are two custom procedures with the same name: 'dance'. It not clear which custom procedure will be called when the 'dance' block on the workspace is executed. 
![screen shot 2017-02-16 at 3 03 22 pm](https://cloud.githubusercontent.com/assets/3409578/23038830/6e1a7ec2-f459-11e6-8b12-20a776e1efaa.png)

This issue becomes even more complicated when moving custom procedures to other sprites. More related info will be documented.

## Exposing more 'Options'
![more-options mov](https://cloud.githubusercontent.com/assets/3409578/23039118/804030aa-f45a-11e6-8b58-bfd14adbe493.gif)
Options Include 
- Add number input
- Add string input
- Add boolean input
- Add text label
- Run without screen refresh toggle

## Adding inputs / labels
![adding props mov](https://cloud.githubusercontent.com/assets/3409578/23039302/1ef84e94-f45b-11e6-9781-8b5f1175c26c.gif)

## Editing inputs / labels
![edit fields mov](https://cloud.githubusercontent.com/assets/3409578/23039577/f1e0284a-f45b-11e6-9ede-779dbca0fd64.gif)

## Deleting inputs / labels
![delete prop mov](https://cloud.githubusercontent.com/assets/3409578/23039397/5cf1c46e-f45b-11e6-80c9-d361c526eedd.gif)

## Check / Uncheck 'Run without screen refresh
![check-uncheck mov](https://cloud.githubusercontent.com/assets/3409578/23039579/f6e59f00-f45b-11e6-9f93-bf08bd49af61.gif)

## Clicking 'ok' to confirm block
![ok-to-block mov](https://cloud.githubusercontent.com/assets/3409578/23039764/cc900398-f45c-11e6-9c56-bcfdfe94b0be.gif)

**Comment by carljbowman** [comment]
Todo:
- [ ] Spec 3.0 'Define' Block
- [ ] Spec 3.0 Using Custom Procedures
- [ ] Spec 3.0 Dragging Custom Procedures to other Sprites
- [ ] Spec 3.0 Dragging Custom Procedures to the Backpack

# Scratch 3.0 - Round 1 - Create a Custom Procedure Behaviors

## Clicking 'Make a Block' opens Dialog
- From within the 'More Blocks' category, user clicks 'Make a block'
![r1 5 2_gui_make-a-block_1](https://cloud.githubusercontent.com/assets/3409578/23228163/9ee1d898-f909-11e6-892d-7e42cab77c4c.png)

- 'Make a Block' dialog opens
![r1 5 2_gui_make-a-block_2](https://cloud.githubusercontent.com/assets/3409578/23228213/be2bafda-f909-11e6-9917-3ff00ef9a691.png)

## Closing 'Make a Block' Dialog
- User can close by clicking transparent background
- User can close by clicking the ( x ) icon in the upper left
- User can close by clicking the 'Cancel' button
![r1 5 2_gui_make-a-block_3](https://cloud.githubusercontent.com/assets/3409578/23228247/dbc83504-f909-11e6-9241-d7ec811c02fb.png)

## 'Naming' a block
1. User clicks the 'text label' field (transparent black)
![r1 5 2_gui_make-a-block_4](https://cloud.githubusercontent.com/assets/3409578/23229014/ad9d0dfa-f90c-11e6-8a20-f09ece78ec4f.png)

2. Once the field has focus the user can edit the text, in this case the user has highlighted 'block'
![r1 5 2_gui_make-a-block_5](https://cloud.githubusercontent.com/assets/3409578/23229210/6f803f14-f90d-11e6-83d1-e8933288c6c9.png)

3. User deletes the text to rename the block
![r1 5 2_gui_make-a-block_6](https://cloud.githubusercontent.com/assets/3409578/23229321/e4567952-f90d-11e6-81de-c1cd682a01a0.png)
- Important to note the default size of the block 'name' field, this is inline with the minimum block width as seen in the specs below. 
  - The block will not grow until the text extends beyond the orange line. <img width="315" alt="screen shot 2017-02-22 at 2 53 12 pm" src="https://cloud.githubusercontent.com/assets/3409578/23229732/5c5f779a-f90f-11e6-9c73-faab845fd6af.png">

  - Or if the text is shorter than the orange line and an input is added, the input start here <img width="301" alt="screen shot 2017-02-22 at 2 49 47 pm" src="https://cloud.githubusercontent.com/assets/3409578/23229772/82c0bdb8-f90f-11e6-9860-a8bcc163c4de.png">

4. User renames block 'dance'
![r1 5 2_gui_make-a-block_7](https://cloud.githubusercontent.com/assets/3409578/23230624/b633d13c-f912-11e6-8812-8270545bf8c6.png)

5. User clicks out of field, so it loses focus
![r1 5 2_gui_make-a-block_8](https://cloud.githubusercontent.com/assets/3409578/23230704/003b9c24-f913-11e6-8884-5f81e30e6ce5.png)

## Exposing more options
By default, 'More options' is collapsed.

1. User clicks 'More Options'
![r1 5 2_gui_make-a-block_9](https://cloud.githubusercontent.com/assets/3409578/23230822/61b63eaa-f913-11e6-95c9-89a222c9589c.png)

2. 'More options' are exposed in an accordion animation. The dropdown arrow flips and the text changes to 'Less options'
![r1 5 2_gui_make-a-block_10](https://cloud.githubusercontent.com/assets/3409578/23231248/21e97740-f915-11e6-8086-7fb4fedaed86.png)

Options Include (different from 2.0)
- Add input: number or text
- Add input: boolean
- Add label
- Run without screen refresh

_Language (e.g. 'Add input: number or text') subject to change._

## Adding inputs / labels
1. User clicking 'Add input: number or text' input. A number/text input is added to the block with the text highlights. 
_Default language that appears in a newly added input will need refinement_
![r1 5 2_gui_make-a-block_11](https://cloud.githubusercontent.com/assets/3409578/23233516/1100ae00-f91d-11e6-8bb1-cb95b095ea36.png)

2. User changes text within the input. 
![r1 5 2_gui_make-a-block_12](https://cloud.githubusercontent.com/assets/3409578/23234072/e707e9e0-f91e-11e6-915f-026344d0cbcb.png)
This eventually will become the reporter block within the 'definition' block. <img width="308" alt="screen shot 2017-02-22 at 4 43 11 pm" src="https://cloud.githubusercontent.com/assets/3409578/23233838/10b8a2b2-f91e-11e6-9832-36c6eef8da54.png"> 
_This is not a block definition design, just a concept sketch to illustrate the point above._
 
3. User adds an addtional label and enters text
![r1 5 2_gui_make-a-block_13](https://cloud.githubusercontent.com/assets/3409578/23234298/a185fa14-f91f-11e6-8130-2b5544c7d951.png)

_In a future iteration we might want to explore the ability to reposition inputs / labels._

## Editing inputs / labels
1. User can navigate between inputs and labels by clicking the element they would like to change.
![r1 5 2_gui_make-a-block_14](https://cloud.githubusercontent.com/assets/3409578/23234511/4dd64580-f920-11e6-85a7-fa2bf38b166a.png)

2. User updates the text they previously entered
![r1 5 2_gui_make-a-block_15](https://cloud.githubusercontent.com/assets/3409578/23234597/98e843ac-f920-11e6-8a0d-63fabca30b7c.png)

## Deleting inputs / labels
1. User accidentally adds a boolean
![r1 5 2_gui_make-a-block_16](https://cloud.githubusercontent.com/assets/3409578/23234814/507cd0a0-f921-11e6-96f8-575fcfa612d2.png)

2. User clicks the delete icon
![r1 5 2_gui_make-a-block_17](https://cloud.githubusercontent.com/assets/3409578/23234882/8e149740-f921-11e6-9d97-b0a9f2fe2b98.png)

## Check / Uncheck 'Run without Screen Refresh'
![r1 5 2_gui_make-a-block_18](https://cloud.githubusercontent.com/assets/3409578/23235114/420966a4-f922-11e6-8673-8e518e5f1d5b.png)

**Comment by MichaelZawadzki** [comment]
Is there any info on the timeline around this feature?

**Comment by rschamp** [comment]
@MichaelZawadzki Yes, currently this is scheduled for the end of the year. Of course we have a lot of plates in the air, so that could change.

**Comment by Kenny2github** [comment]
I’m don’t really like the fact that number and text inputs are combined - it adds ambiguity to which input type the block shows up as (is it number or string?) and removes the ability to ensure a number for inputs that should be numbers.
