### ISSUE TITLE
Angle picker doesn't pick angles

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#636]
I guess this probably happened during a merge?

**Comment by tmickel** [comment]
This is quite mysterious...it seems that the mousemove event is being bound, but no event is ever called.

**Comment by tmickel** [comment]
Seems the mousemove event is getting lost here:
https://github.com/LLK/scratch-blocks/blob/develop/core/utils.js#L121

I'm surprised this isn't affecting google/blockly. Thoughts @rachel-fenichel ?

**Comment by tmickel** [comment]
It seems to work after setting `opt_noCaptureIdentifier`...does that make sense?

**Comment by rachel-fenichel** [comment]
The problem is that there's no mousedown or touchstart even that we're listening to to start the drag, so this line isn't getting hit: https://github.com/LLK/scratch-blocks/blob/develop/core/touch.js#L197

As a result, the touch identifier is staying null and the mousemoves are being ignored.

As a general rule, setting opt_noCaptureIdentifier will make these sorts of problems go away, but will break multitouch.

**Comment by tmickel** [comment]
By break multitouch, do you mean dramatically?

**Comment by rachel-fenichel** [comment]
Probably dramatically.  If noCaptureIdentifier is true, it won't check whether the touch is coming from the currently active finger, which can put you back to the state that blockly has previously been in.

In this case it may be okay, because we want this to work on any mousemove, not just ones that are part of an active drag.  I'll have to test it on mobile to be sure.

**Comment by tmickel** [comment]
Assigning Carl for thoughts about hovering.

**Comment by rachel-fenichel** [comment]
Fixing in mainline: https://github.com/google/blockly/pull/676
