### ISSUE TITLE
iOS Flyout Freezing

### ISSUE THREAD

**Issue by MichaelZawadzki** [LLK/scratch-blocks#715]
I am noticing that on iPads (iOS 9 iPad 4 Safari) that the Flyout freezes up very quickly when trying to use it. Scrolling operations will quickly result in this (even a simple scroll can do it sometimes). 

When this happens the flyout and workspace are frozen. Additionally drags on the workspace then start to scroll the entire page. There are no console errors.

I can see this happen with both current demos:
https://utils.asun.co/scratch-blocks/tests/vertical_playground.html
http://llk.github.io/scratch-vm/#

**Comment by thisandagain** [comment]
Thanks for reporting!

**Comment by rachel-fenichel** [comment]
Sounds like another multitouch bug.  Do you have any more specific steps for reproducing it?

**Comment by MichaelZawadzki** [comment]
Multitouch is not required to trigger the bug, meaning I'm only using 1 finger and so 1 touch max at a time. 

I literally just scroll the flyout downwards... it usually happens right away as I'm nearing the bottom of the category... but not always... though a bit more scrolling triggers it quickly. You should be able to reproduce this by just scrolling up and down. 

Let me know if there is something specific you would like to know. I'll also see if its isolated to a specific iOS version or not.

**Comment by rachel-fenichel** [comment]
Are you scrolling with the scrollbar in the flyout, or the flyout background, or one of the blocks?  Can it happen in any category?  Does it happen if you scroll the main workspace, or only the flyout?

Interesting that it doesn't happen every time.  That's a bit concerning.

What I meant by multitouch is "my implementation of multitouch support".  There's a difference in how android and ios assign identifiers to touch events that means that some failures are completely silent in android but very visible in iOS.  Freezing up so that nothing responds and the whole page scrolls instead is consistent with this class of bugs.

**Comment by MichaelZawadzki** [comment]
Also on iOS 10.

So it seems it breaks on the 2nd touch on the flyout... (this explains why I thought it was happening near the bottom of the scroll... since here I need to lift my finger to drag further... triggering the 2nd touch).

So steps to reproduce (100% repro as I can tell):
1) Scroll the flyout a little
2) Stop scrolling
3) Start scrolling again -> notice it won't scroll anymore 

Good questions btw... indeed it DOES NOT happen if you touch on the block within the flyout... nor the scroll-bar on the side of the flyout... but ONLY when touching the flyout background itself. 
Happens in any category (have not seen any category that's immune to it).

Main workspace doesn't trigger this bug. So only flyout background.

**Comment by rachel-fenichel** [comment]
Great, thanks for the info.  I'll take a look!

**Comment by MichaelZawadzki** [comment]
Thanks for taking a look!
