### ISSUE TITLE
Make NPM build script work on Windows

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-blocks#718]
It uses Mac/Linux-Slashes which could be avoided it calls to the module instead of its bat/sh file.

**Comment by thisandagain** [comment]
@rschamp I believe you mentioned that we had a reason for including the path explicitly (which unfortunately still causes the NPM scripts to break on Windows. Could you clarify?

**Comment by rschamp** [comment]
Leaving out the explicit path caused path problems when running `npm install` from a project using scratch-blocks as a dependency with `npm link`.  However I hit this when we were relying on everything installed via Github rather than npm, so I will see if the changes I've made since then have alleviated the issue.
