### ISSUE TITLE
Github Pages - Deploy playgrounds to GH pages

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#744]
- [x] Setup 
    - [x] https://llk.github.io/scratch-blocks
    - [ ] https://llk.github.io/scratch-blocks/playgrounds/horizontal.html
    - [ ] https://llk.github.io/scratch-blocks/playgrounds/vertical.html
- [x] Update playgrounds to use compressed blocks or solve issue with closure-library dep.
- [x] Update travis config to deploy on merge to `develop`

**Comment by ghost** [comment]
Well, i managed to do a gh-pages branch that works.
It uses Compressed Playgrounds (even the Horizontal one)
Note: the travis config was not updated in the branch
https://joaoh1.github.io/scratch-blocks (The Links in the page will not work because it's prepared for PR)
https://joaoh1.github.io/scratch-blocks/playgrounds/vertical.html
https://joaoh1.github.io/scratch-blocks/playgrounds/horizontal.html
I was going to make a PR for this, but there was no "gh-pages" branch.
EDIT: I fixed the Playground links

**Comment by thisandagain** [comment]
Resolved in https://github.com/LLK/scratch-blocks/pull/755

**Comment by rschamp** [comment]
Resolved in #755 (and fixed again in 279fb6331a3f93fb91d97885c25236b92afea823). Addendum to the previous plan, the links are:
*  https://llk.github.io/scratch-blocks/playgrounds/tests/vertical_playground.html
*  https://llk.github.io/scratch-blocks/playgrounds/tests/horizontal_playground.html
