### ISSUE TITLE
/dist/horizontal.js doesn't include full blockly.

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-blocks#746]
It only has:
- Xml
- Mutator
- Map
- Msg

**Comment by TheBrokenRail** [comment]
Do you have any ideas on a temporary fix for this?

**Comment by rschamp** [comment]
The files in `/dist` are only necessary for module imports where you need Blockly to be scoped to your module rather than a global. If you don't care about the global scope, you can just include the files in your page in the same manner as the playgrounds and use the Blockly global that way.

**Comment by TheBrokenRail** [comment]
My question is, why does the vertical file load full blockly and blocks and the horizontal file only load stuff for mutators, msg, xml, and map?

**Comment by rschamp** [comment]
We haven't used/tested `/dist/horizontal.js` since we're focused on the Scratch 3.0 prototype which uses vertical blocks. So the build process for `/dist/horizontal.js`  could very well be broken. The build is described in `webpack.config.js` — then follow the path of shims in `/shim`. Run `npm run prepublish` to rebuild.

**Comment by TheBrokenRail** [comment]
Oops, this was just a issue with testing, closing issue.
