### ISSUE TITLE
Figure out how shadow blocks and variable blocks get along.

### ISSUE THREAD

**Issue by picklesrus** [LLK/scratch-blocks#769]
https://github.com/google/blockly/commit/08efd1381c575f304d000e44060135e35f7ed013 which disallows shadow blocks in variables was recently committed to blockly.  This breaks the current scratch-blocks assumptions.  After talking with @rachel-fenichel, I've reverted that commit in the merge, but we wanted to track this going forward as some of the variable work is done.

**Comment by RoboErikG** [comment]
Just to capture some of the internal discussion, on Blockly we disallowed variables in shadow blocks because when you delete a variable that is in use we delete all blocks that use that variable (with confirmation). This made shadows inconsistent since they can't be deleted, so we decided to just not allow variables in shadows.

Scratch handles deleting a variable differently, so that reasoning doesn't apply.

**Comment by picklesrus** [comment]
Tis is essentially a duplicate of #573. When that's done, this won't be a problem anymore.
