### ISSUE TITLE
Undo/Redo UI buttons in vertical playground is broken.

### ISSUE THREAD

**Issue by cdeng-amplify** [LLK/scratch-blocks#773]
### Expected Behavior

Undo and Redo buttons in the vertical playground should work exactly as the context menu.

### Actual Behavior

When undo and redo buttons are clicked repetitively in the vertical playground, the blocks in the workspace are incorrectly restored.

### Steps to Reproduce

1. place a repeat block in the workspace.
2. place another block inside the repeat block as shown in the first attachment.
3. detach the inner block of the repeat block.
4. press undo (in the left side menu) and notice the block goes back inside the repeat block. (correct behavior)
5. press redo (in the left side menu) and notice the block now goes to a different location then it was before (incorrect behavior)
6. now press undo again (in the left side menu) and notice the inner block now is in a broken state.

![screen shot 2017-01-23 at 10 06 46 am](https://cloud.githubusercontent.com/assets/3731340/22209394/4efff110-e154-11e6-8585-7896b4947ecc.png)
![screen shot 2017-01-23 at 10 07 33 am](https://cloud.githubusercontent.com/assets/3731340/22209395/4f04ee72-e154-11e6-9abb-918634d7e933.png)

NOTE: the Undo and Redo works as expected when using the context menu.  

### Operating System and Browser

_e.g. Mac OS 10.11.6 chrome 55.0.2883.95

**Comment by thisandagain** [comment]
@rachel-fenichel @picklesrus This is a little odd. Any thoughts?

**Comment by rachel-fenichel** [comment]
Nothing comes to mind.

**Comment by picklesrus** [comment]
Yeah, this is weird. The behavior using the right-click menu on the workspace to undo/redo (instead of the buttons on the playground page) seems correct though.

**Comment by cdeng-amplify** [comment]
I have found that if the the right click context menu is used first to perform undo/redo task, then use the undo/redo buttons, then the behavior is correct. The bug only occurs if the context menu is not used at all.

**Comment by samelhusseini** [comment]
We are also running into this.

**Comment by davidaylaian** [comment]
Not sure if this is the same problem, but it seems similar enough so I'm commenting it here instead of opening a new issue. If I should open an issue, tell me.

### Steps to Reproduce

In the vertical playground:
Not sure if I found a new
1. Make this:
![screenshot from 2017-12-22 21-13-36](https://user-images.githubusercontent.com/22228595/34316150-1358e012-e75d-11e7-8056-9758dfb57749.png)
2. Move the `abs of list` block out of the `move x steps`
3. Move it back in
4. Undo
5. Move the  `abs of list` block anywhere

### Expected Behavior

When following the steps to reproduce, the undo should work as expected and not disconnect the `abs of list` block.

### Actual Behavior

![screenshot from 2017-12-22 21-24-01](https://user-images.githubusercontent.com/22228595/34316234-8e6eaccc-e75e-11e7-8bdc-e0bf02b8e8b1.png)
Interestingly, moving around the `abs of     ` will also move the relative position of the list.

### Operating System and Browser

Firefox 57.0.1 and Chrome 63.0.3239.108 Linux
