### ISSUE TITLE
Browser right click menu appears in block palette

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-blocks#795]
### Expected Behavior

The block menu (or no menu, depending on where you click) appears. No system menu accompanies it.

### Actual Behavior

The block menu appears (if you right clicked on a block), with the system menu also displayed.

### Steps to Reproduce

Open any location with scratch-blocks visible and right-click on the block palette.

### Operating System and Browser

macOS 10.12, Chrome 56; the issue is browser independent (repro'd on Firefox and Safari as well).

**Comment by thisandagain** [comment]
Nice catch @liam4 !

**Comment by Tymewalk** [comment]
@thisandagain How do we prevent the system menu from appearing when right-clicking on the workspace? I think we just need to add the same thing to the flyout/other parts of the screen.

**Comment by rachel-fenichel** [comment]
Please hold off on working on this for a bit.  I'm reworking clicking and dragging fairly radically in Blockly, so changes will be rapidly invalidated.

**Comment by towerofnix** [comment]
@rachel-fenichel May want to remove the "help wanted" tag, then? :)

**Comment by rachel-fenichel** [comment]
Alrighty, I understand why this is happening, but there are decisions to make.

This code used to block the system menu in all of blockly: https://github.com/google/blockly/blob/master/core/inject.js#L283

```
  var svg = mainWorkspace.getParentSvg();

  // Suppress the browser's context menu.
  Blockly.bindEventWithChecks_(svg, 'contextmenu', null,
      function(e) {
        if (!Blockly.utils.isTargetInput(e)) {
          e.preventDefault();
        }
      });
```

but we changed the SVG structure so that the workspace's parent SVG is no longer the parent of the flyout SVG.  I can fix this with 

```  
var svg = mainWorkspace.getParentSvg();

  // Suppress the browser's context menu.
  Blockly.bindEventWithChecks_(svg.parentNode, 'contextmenu', null,
      function(e) {
        if (!Blockly.utils.isTargetInput(e)) {
          e.preventDefault();
        }
      });
```

That suppresses the browser context menu for all of Blockly, and then you can see that the block context menu was there--it was just under the browser context menu.

@thisandagain @carljbowman what behaviour on right-click do you want on the background of the block palette?  What about the category picker?  Is suppressing the system menu sufficient, or do you want a different right-click menu there?  Showing a different context menu isn't hard, so it's a question of what items it would have.

**Comment by rachel-fenichel** [comment]
Another question: does right-clicking on any of those locations hide the widget div, if it's open, even if we don't show a context menu?

**Comment by rachel-fenichel** [comment]
Fixed in https://github.com/google/blockly/pull/1018
