### ISSUE TITLE
Use variables to define colors in default xml

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-blocks#802]
This would make it easier to change categories colors with out have to change it in two places.
# Current
```"colour='#000000'"```
# Proposed
```"colour='" + Blockly.Colours.thing.colour + "'```

**Comment by mrjacobbloom** [comment]
Or better yet, if we ever switch to styling blocks with CSS, style them with the same CSS that are used for blocks.

**Comment by Tymewalk** [comment]
That's a good idea. Does anybody have a link to where these variables are held? I could make a PR.

**Comment by TheBrokenRail** [comment]
the variables are in ```Blockly.Colours``` so ```Blockly.Colours.motion.primary``` would be the primary color for motion. This is defined in [https://github.com/LLK/scratch-blocks/blob/develop/core/colours.js](https://github.com/LLK/scratch-blocks/blob/develop/core/colours.js).

**Comment by rschamp** [comment]
I don't think we actually want this change, because it would make copying the default toolbox harder to do. It is more portable if we don't use variables. The default toolbox is a stop-gap solution that will be removed when we update the management of the toolbox (e.g. when you select a sprite vs the stage).

Also, to clarify the contributor guidelines: we will not accept PRs if the issue they are filed against is not accepted by the Scratch team. Please only submit PRs if the issue has a "help wanted' label, or is otherwise approved as a wanted feature by the maintainers.  We really appreciate your contributions and your enthusiasm working on Scratch 3.0. Unfortunately we only have so much time, so we need to conserve how much of it we spend responding to issues and PRs. Thanks for your understanding.
