### ISSUE TITLE
Workspace pattern

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#817]
An initial pattern for the workspace. We certainly should explore more options, but it would be good  to have something in place for the Animate a Name/Word playtest.

![r1 2_gui_animate-prototype](https://cloud.githubusercontent.com/assets/3409578/23512601/2d4cf4de-ff2f-11e6-94d5-41ff35011436.png)

Sample 
<img width="231" alt="screen shot 2017-03-02 at 10 01 47 am" src="https://cloud.githubusercontent.com/assets/3409578/23512632/4a68e10e-ff2f-11e6-82d7-d75cc5a7b8e9.png">

Assets: [patterns.zip](https://github.com/LLK/scratch-gui/files/814153/patterns.zip)
Included a repeatable pattern tile in a few different formats: svg and png. Knowing the workspace we may want to use the png for performance. 

---
Moved from LLK/scratch-gui#153
/cc @carljbowman @thisandagain

**Comment by paulkaplan** [comment]
@thisandagain Looked into this a bit. I _believe_ we'll need to go through javascript to create a dot pattern similar to how blockly creates the default grid pattern because we will need to tie the zooming in/out with the pattern sizing. I was able to cook this up pretty easily, though:
<img width="1381" alt="screen shot 2017-03-10 at 5 06 33 pm" src="https://cloud.githubusercontent.com/assets/654102/23815024/fac506ec-05b3-11e7-9454-f2eda592ba84.png">

The relevant code for that is in two places, one for generating the pattern (https://github.com/LLK/scratch-blocks/blob/develop/core/inject.js#L187-L209) and another for updating the pattern based on scaling https://github.com/LLK/scratch-blocks/blob/develop/core/workspace_svg.js#L1658-L1688

**Comment by thisandagain** [comment]
@paulkaplan That sounds great to me. Thanks for investigating.

@carljbowman Having the background zoom is interesting / possibly desirable. Any thoughts?

**Comment by rachel-fenichel** [comment]
https://developers.google.com/blockly/guides/configure/web/grid

**Comment by mrjacobbloom** [comment]
note that @paulkaplan's pattern doesn't match the original (where every other row is shifted by 50%)

**Comment by paulkaplan** [comment]
@rachel-fenichel welp eventually I'll learn to check the docs first ;)

**Comment by rachel-fenichel** [comment]
@Airhogs777 is right that they aren't quite the same, but that just means y'all have some decisions to make
-- is the grid configurable by developers?
-- are you super attached to the row-by-row offset?  If you are you can change the pattern definition to include a rotation, but then you probably want to cap the length of the lines so the background won't look funny.
-- do you want to keep the snap-to-grid behaviour?

**Comment by paulkaplan** [comment]
Yeah I was just wondering about how the row offset would interact with snap-to-grid. Just using the grid configuration @rachel-fenichel linked you can make some nice patterns.
<img width="1305" alt="screen shot 2017-03-10 at 5 23 18 pm" src="https://cloud.githubusercontent.com/assets/654102/23815501/99dc62be-05b6-11e7-89d4-66b82308ee54.png">
Is using 
```    
Blocks.defaultOptions = {
    ...
    grid: {
        spacing: 20,
        length: 2,
        colour: '#ddd',
    }
    ...
}
```
from scratch-blocks/containers/blocks
