### ISSUE TITLE
Horizontal block parameter numerical selection does not display correctly

### ISSUE THREAD

**Issue by msintov** [LLK/scratch-blocks#826]
### Expected Behavior

In a horizontal project, when I enter a number to set the parameter for blocks such as the loop or timer blocks, the number I enter should display in the selected number area at the bottom of the script. This should work for both desktop browsers as well as on mobile devices that show a number dropdown.

### Actual Behavior

After I enter the number, the previously shown number still shows.

### Steps to Reproduce

1. Load horizontal_playground.html on a desktop browser (such as Chrome 56.0 on a Mac)
2. Drag the loop block to the stage
3. At the bottom of the loop block, select the default '4' and type '9' (to replace the '4')
4. Hit return or click away from the block
5. Observe that the number changes back to 4

### Operating System and Browser

Mac OS 10.11.6 Chrome 56.0

**Comment by picklesrus** [comment]
I noticed this as well.  I believe https://github.com/google/blockly/commit/01ab0b4ab6bbae495c09d6ed6f553f9eb9e81b9f combined with how it was merged from upstream broke this.

That CL refactored where some of the field render code was called. Vertical blocks didn't break because block_render_vertical's render function (which, iiuc, is called after you change the value) eventually calls getSize on the field(which calls field's render) but block_render_horizontal's render function never ends up calling render on fields so they keep the old value.

I'm still not 100% sure of how wide this problem is (e.g. is it just text input fields?) and if this is the right way to fix it, so I'm not ready to send that as a PR, but if you're looking for a quick work around/hack, you can force a render of the fields from block_svg_horizontal's render function with this code:
```js
for (var i = 0, input; input = this.inputList[i]; i++) {
    for (var j = 0, field; field = input.fieldRow[j]; j++) {
      if (field instanceof Blockly.FieldTextInput) {
        field.render_();
      }
    }
  }
```

**Comment by msintov** [comment]
@picklesrus Thank you so much! Works great for my needs. I appreciate it!

**Comment by zhlella** [comment]
Wow, it's good ! Thank you ！I saw it when I needed it！^_^

**Comment by picklesrus** [comment]
I dug into this some more and there are a couple of approaches that could work.  As I mentioned above, the difference between the horizontal blocks and the vertical blocks is a call to re-render the field from the block's render().  So far the two solutions I can think of are:
1. Force the horizontal blocks to re-render text fields from block_render_horizontal's render function (see code snippet above).
2. In FieldTextInput's widgetDispose_ (called when you click away from the input box) I'd change the render call to re-render just the field instead of the whole block. In code [this line](https://github.com/google/blockly/blob/master/core/field_textinput.js#L307) would change from
`thisField.sourceBlock_.rendered && thisField.sourceBlock_.render();`
to
`thisField.sourceBlock_.rendered && thisField.render_();`

Personally, I kind of like 2 better because it seems more explicit. But, I'm slightly worried that I'm missing reasons we want to render the whole block.  My understanding is that vertical blocks change their size as the user types so we don't need to re-calculate/render when you click out. Horizontal blocks don't change size based on the length of the text input so the re-render of the horizontal block should be irrelevant.

@rachel-fenichel @thisandagain @paulkaplan thoughts?

**Comment by thisandagain** [comment]
Number two makes more sense to me as well. We re-render the whole block in some instances (like selecting a color or setting the motor speed) as we update the block icon, but if this is specific to the FieldTextInput then I can't think of a reason to isolate rendering to the field.

**Comment by simeon-dobrikov-3D-depth** [comment]
If you replace in field_textimput.js 
this.sourceBlock_.rendered && this.sourceBlock_.render();
to 
this.sourceBlock_.rendered && this.render_();
It will work again at least in my case.
