### ISSUE TITLE
Duplicated blocks should be attached to the mouse cursor

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#828]
### Expected Behavior

- After duplication the new blocks should be attached to the mouse cursor (e.g. Scratch 2.0)

### Actual Behavior

- Blocks are directly added to the workspace

**Comment by rachel-fenichel** [comment]
How does this work on touch?

**Comment by thisandagain** [comment]
I don't think we'll have duplication on touch.

**Comment by rachel-fenichel** [comment]
As in, you won't have it in the context menu as an option?

**Comment by thisandagain** [comment]
I think we are leaning towards not having any context menus for touch environments.

**Comment by towerofnix** [comment]
> I don't think we'll have duplication on touch.

Well, sure, but there's still the "stamp"/duplicate button:

![screen shot 2017-03-07 at 4 50 57 pm](https://cloud.githubusercontent.com/assets/9948030/23677381/44005f24-0356-11e7-8358-155e4869f7cc.png)

Duplicating blocks is an incredibly useful feature. Removing all ways of using it would quite reduce productivity – for instance, implementing the distance formula as this would be much more inconvenient:

![](https://cloud.githubusercontent.com/assets/9948030/23677532/e47f2192-0356-11e7-9fbf-a578a01315d8.png)

Making this just once would already be more tedious without block duplicating functionality, and many users simply don't know about custom blocks – so they'd have to rewrite this entire piece of code, all by hand (..literally.. 😛 ), whenever they want to get the distance between two points!

And it's not like that's the only use case of duplication. Suppose I have a script such as this one:

![demo](https://cloud.githubusercontent.com/assets/9948030/23677855/306ef5cc-0358-11e7-9170-93a87bf2b5cd.png)

Well, you know, it's a relatively complicated script. But it's definitely a realistic one, for a game!

I used duplicate multiple times while making that:

* When using the "initialize enemy class" block.
  * While making the first block, "initialize (blue slime)", I would have used copy/paste to duplicate the "(number) * difficulty" block.
  * While adding more enemies, I used copy/paste to duplicate the entire "initialize enemy" block, which contained the "(number) * difficulty" blocks.
* When making the "initialize enemy class" block's script.
  * I duplicated the "add (block) to enemy class data" block multiple times.
* In the future, when adding more locations.
  * I would duplicate the "set (location ID) to" and "set (location difficulty) to" blocks, to keep track of the variables I'd need to set up for each location.

Imagine writing *the entire script* by hand, without using the duplicate feature. It'd be *very* tedious.

I imagine we're going for a relatively seamless experience between the computer and mobile versions of Scratch, which currently run via the exact same code, right? In my opinion, not being able to duplicate blocks on mobile would be a very big issue with the mobile edition of Scratch.

And at this point, it's not even difficult to keep duplication functionality within Scratch on any device – since there's still that "stamp" button in the menu bar!

(edit: clarified by adding quote to top)

**Comment by thisandagain** [comment]
@rachel-fenichel Is this a behavior you would want in Blockly as well?

**Comment by rachel-fenichel** [comment]
Nope, there's no reason to change that UI for all of our developers and users downstream.

Implementing this will probably be much simpler after I finish cleaning up dragging.  (See the dragging branch on google/blockly for the start of that work.)

**Comment by thisandagain** [comment]
@rachel-fenichel Sounds good. I'll keep this in the backlog in the meantime. Would you mind dropping a note in here once you feel like the dragging changes upstream are ready for us to evaluate?

**Comment by rachel-fenichel** [comment]
Will do.

**Comment by rachel-fenichel** [comment]
I just landed the dragging refactor.  I'll take another look at this.

**Comment by towerofnix** [comment]
Merged PR #1001 resolves this issue. Should this be closed?

**Comment by rschamp** [comment]
Yep, thanks @towerofnix!
