### ISSUE TITLE
Block detach distance threshold is too large

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-blocks#854]
### Expected Behavior

When two blocks are connected, and you drag the bottom one down to detach, I expect to be able to release the block after dragging it beyond the edge of the insertion marker.

### Actual Behavior

In order to detach the block, I have to drag past the ~~shadow~~ insertion marker, about twice its height. This gif shows dragging the block almost this far, and it still snaps back:

![block-detach-distance](https://cloud.githubusercontent.com/assets/567844/24158635/42f090a8-0e33-11e7-946c-8d2bcc5c48c6.gif)

### Steps to Reproduce

Attempt to disconnect two blocks by dragging the bottom one downward.

### Operating System and Browser

Mac OS 10.11.6 Chrome 57

**Comment by rachel-fenichel** [comment]
Code pointer:  https://github.com/LLK/scratch-blocks/blob/develop/core/block_svg.js#L1149

I would play around with this when the block is in the middle of a stack to make sure you want to change it.  I think it's protecting against jumping around as the blocks shift to accommodate the insertion marker*.

*not a shadow.  Shadow has a specific meaning in Blockly.

**Comment by tmickel** [comment]
Original issue with video: https://github.com/LLK/scratch-blocks/issues/290

you might be able to come up with a more clever solution :) e.g., maybe the size could be minimized depending on the size of the insertion marker (smaller for vertical than horizontal), or maybe you could only apply this rule when the insertion marker is in the middle of a stack

**Comment by rachel-fenichel** [comment]
Related: this transitions almost* directly from before the stack to wrapping the second block in the stack.

*almost because when it does wrap the whole stack, it does it for a frame or two and it's a pretty nasty flicker, but finding that space intentionally is almost impossible at normal zoom.

![63e22b70-ac8c-473f-a9b2-f28165ac3b43](https://user-images.githubusercontent.com/13686399/26859267-659659ea-4aeb-11e7-88cd-716800b8fe7d.gif)
