### ISSUE TITLE
Touch on Edge does not drag blocks

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [LLK/scratch-blocks#876]
### Expected Behavior

When I touch and drag blocks on Edge, the blocks should move.

### Actual Behavior

Edge triggers the "back" action - as if touch events don't call `preventDefault` or something.

### Steps to Reproduce

On a touchscreen device running Edge, attempt to drag blocks using touch

### Operating System and Browser

Windows 10 15063.138, Edge 40.15063.0.0

**Comment by rachel-fenichel** [comment]
This is a Blockly issue, tracking here: https://github.com/google/blockly/issues/943

Edge uses pointer events instead of touch events and mouse events.  Blockly was originally built with mouse events, with touch event handling added on.  Safari will never support pointer events, so we can't move fully to them, but we should eventually be able to support them.

**Comment by MegaApuTurkUltra** [comment]
Pointer events are objectively better than touch events. How do you think people are going to use their fancy styli in scratch 3 without pointer events?

**Comment by rachel-fenichel** [comment]
Hey there,

Pointer events vs touch events is actually a really interesting space.  

The specification for pointer events is a living [document](https://w3c.github.io/pointerevents/).  It's hosted on the w3c github, but it's in [active](https://github.com/w3c/pointerevents/pulse/monthly) development.  You can flip through the [issues](https://github.com/w3c/pointerevents/issues) there to get an idea of what sorts of complicated cases they're trying to deal with.

There are some pretty major caveats in the spec as well.  For instance: 

> This specification does not provide any advice on the expected behavior of user agents that support both Touch Events (as defined in [TOUCH-EVENTS]) and Pointer Events. For more information on the relationship between these two specifications, see the [Touch Events Community Group](https://www.w3.org/community/touchevents/).

And this one, which is relevant to any thoughts of multitouch or pinch-to-zoom:
> Some user agents support touch actions triggered by interactions of multiple concurrent pointers (e.g. multi-touch). Methods for processing or associating the touch-action values of multiple concurrent pointers is out of scope for this specification.

And as mentioned above, Safari won't support pointer events at all ([and were snarky in saying so](https://lists.webkit.org/pipermail/webkit-dev/2012-December/023050.html)).

Basically, pointer events are pretty excellent but switching to using them isn't simple for us because our core interactions don't map well to what pointer events are optimized for.  While we may be able to use the Pointer Events Polyfill to switch fully to pointer events, we need to evaluate that in terms of compressed size (among other things) and make sure that it doesn't blow up our code.  

We are not ignoring them, but I have not yet had the bandwidth to work out a clean, maintainable solution for our use case.

----------

If any of this sounded interesting to you, I encourage you to go play around with touch events and pointer events.  It's a wild and wacky world, where you have to pay attention to all sorts of browser-specific behaviour, but it'll give you a new perspective on just about every interaction with your computer or phone.

**Comment by MegaApuTurkUltra** [comment]
Scratch with a stylus would be a use-case I'd really like to see happen. Unfortunately, without pointer events you can't detect stylus pressure, buttons, or upside down "erase mode"

Switch to pointer events and use touch events exclusively as a fallback on Safari.

**Comment by rachel-fenichel** [comment]
It looks like you're responding to my comment from two days ago.  You should read my longer comment from yesterday so that you have context on this issue.

**Comment by AnmAtAnm** [comment]
Pointer event have been implemented and this appears solved.
