### ISSUE TITLE
Workspace panning is extremely slow

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [LLK/scratch-blocks#882]
### Expected Behavior

Workspace panning should be smooth.

### Actual Behavior

Workspace panning is about 2 fps.

### Steps to Reproduce

Open https://llk.github.io/scratch-gui/. Attempt to pan with mouse or touch.

### Operating System and Browser

Windows 10, Chrome 58. Quad core 2.6 ghz i7 with 16 gb ram

**Comment by rachel-fenichel** [comment]
Panning performance on llk.github.io/scratch-gui isn't strictly indicative of scratch-blocks performance.  A better test is on https://llk.github.io/scratch-blocks/playgrounds/tests/vertical_playground.html, where performance is all right with an empty workspace.

**Comment by MegaApuTurkUltra** [comment]
That pans better. Why is scratch-gui drastically different?

**Comment by rachel-fenichel** [comment]
I would guess that scratch-vm and scratch-gui are not at all optimized at this point, since they're focusing on getting features in.  You can also look at scratch-vm to see a FPS meter: https://llk.github.io/scratch-vm/

If you're in Chrome you can open up developer tools and go to the "performance" or "timeline" tab (depending on your version) to get a timeline of what's happening as you drag.  Other browsers should have this as well, somewhere in developer tools.

I grabbed a timeline for a bit of dragging the workspace around in scratch-gui.  It looks like this:
![image](https://cloud.githubusercontent.com/assets/13686399/25863737/cd097180-34a1-11e7-8fa3-2f5cbf87f8dd.png)

Green is painting--in this case, compositing layers.  The green chunks are each about 150ms, which is enough to cause significant jank.

Here's a similar drag in the vertical playground:
![image](https://cloud.githubusercontent.com/assets/13686399/25863831/1cc6b296-34a2-11e7-833b-4920d842ef8e.png)

Notice that there's significantly less total green, both in the timeline and in the pie chart in the lower left hand corner.  So something in scratch-gui is triggering layer compositing on every mouse move, which is expensive.

[Here's](https://www.html5rocks.com/en/tutorials/speed/layers/) a nice summary of layering, though note that it's from 2013.  Details may be completely different now, but the ideas should be the same.

**Comment by rschamp** [comment]
Moved to LLK/scratch-gui#353
