### ISSUE TITLE
Can't delete blocks

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#912]
### Expected Behavior

- Dragging a block into the palette will cause it to be deleted

### Actual Behavior

- Occasionally, dragging a block into the palette will result in it being placed behind the pallete

### Steps to Reproduce

- I haven't been able to find a reproducible case yet. Both @ericrosenbaum and I have seen it over the past few days

### Operating System and Browser

MacOS 10.12.4 | Chrome Version 58.0.3029.110 (64-bit)

/cc @ericrosenbaum @paulkaplan @rachel-fenichel

**Comment by rachel-fenichel** [comment]
You are probably grabbing the block on the right side of the block and dragging it so that the origin of the block is over the flyout, but the cursor isn't.  The deletion state depends on the position of the cursor.

We can change that if you want, but it needs to be an explicit change.

If that's not the cause of the bug, let me know and I can debug further.

**Comment by thisandagain** [comment]
Nope. I've certainly seen it when both the cursor and the entire block are over the palette.

**Comment by rachel-fenichel** [comment]
:+1: I'll take a look.

**Comment by towerofnix** [comment]
I've noticed this as well.

I think the most reproducible cause of this is to go into a separate editor tab (e.g. "costumes" or "sounds") and then go back into "scripts". Blocks will no longer be able to be deleted (even ones newly dragged out from the palette, that haven't even been dropped into the workspace – i.e. grab a new block from the palette, then release it while over the palette - it won't be deleted).

**Comment by paulkaplan** [comment]
@liam4 Yup that looks like it works to reproduce. 

1. Load https://llk.github.io/scratch-gui/ fresh
2. Drag a block out onto the workspace.
3. Click "Costumes"
4. Click "Scripts" 
5. Try to drag the block back into the toolbox, but it cannot be deleted

---

Update 1: Investigating a bit further, here are a few things that **do not** cause this to happen:
 - changing from sprite to background (which causes a whole workspace update)
 - using the show/hide buttons in the playground (setVisible is one of the things that happens when changing tabs, but doesn't seem to be solely responsible)

So far I haven't been able to reproduce in the playground.

---
Update 2: It certainly is being caused by the use of `workspace.setVisible()` when changing tabs. When I remove that code, it works. We we added that in https://github.com/LLK/scratch-gui/pull/368 in order to prevent block squashing. However, it isn't just `setVisible()` on its own, because calling that directly (the way the playground show/hide buttons do) does not cause the same problem. I'm curious if it is because of a timing issue, where the tab switches either before or after setVisible is called, and calling setVisible(false) when it is already hidden causes some horrible measurement problem? Will investigate further.

---
Update 3: Ok here is a way to reproduce it in the scratch-blocks playground:
1. Open the playground http://llk.github.io/scratch-blocks/playgrounds/tests/vertical_playground.html
2. Drag a block out
3. Click "Hide"
4. Resize the window (or manually trigger a window resize event using `            window.dispatchEvent(new Event('resize'));`)
5. Click "Show"
6. Can no longer drag block into the flyout

That may seem like an unusual sequence, but it is actually exactly what we were doing in the workspace update (triggering a window resize, then setting visible to true). That is why in scratch-gui you do not have to resize the window to see this effect, we happen to always be doing it. We can fix that by reordering the resize/setVisible, which fixes the "happens every time no matter what" problem on the GUI. But the "window resize when hidden breaks deleting" looks like a proper scratch-blocks bug. I'll make the adjustment in the gui to prevent the majority of occurrences right now. (https://github.com/LLK/scratch-gui/pull/403)

**Comment by rachel-fenichel** [comment]
This looks like a missing call to workspace.recordDeleteAreas, which is only exposed by the correct combination of calls.  Thanks @liam4 and @paulkaplan for the detailed repro steps.
