### ISSUE TITLE
Insertion marker disconnects C shaped blocks when dragging with a block that has no prev or next statements

### ISSUE THREAD

**Issue by samelhusseini** [LLK/scratch-blocks#946]
### Expected Behavior

Insertion marker shouldn't disconnect blocks when a block with no previous or next statement hovers over a number of nested C shaped blocks. 

### Actual Behavior

Insertion marker disconnects the C shaped blocks

### Steps to Reproduce

Easiest repro is to 
go to https://github.com/LLK/scratch-blocks/blob/develop/blocks_vertical/control.js#L60
control_forever, and remove "previousStatement": null,

Go to the playground and drag a number of C shaped blocks (eg: repeat 10) and nest them. 
Then drag a control -> forever block and drag that over each of the nested repeat blocks. 

![insertionmarkers_issue](https://user-images.githubusercontent.com/16690124/27110662-c860f6c4-505f-11e7-81bd-f76c6927d38c.gif)

### Operating System and Browser

Mac OS 10.12.3 Chrome 58.0.3029.110

**Comment by rachel-fenichel** [comment]
The blocks being connected to don't even need to be c-blocks for this bug to happen.

![a4af5cb0-bc55-4539-887c-59a098784f99](https://user-images.githubusercontent.com/13686399/27408511-eea4e36c-5691-11e7-947b-d5381c042598.gif)

The problem is when you have a block with a statement input but no previous connection.  

I think the desired behaviour is to allow inserting around the entire stack, but not allow inserting around substacks.  That would be similar to what we do with end blocks and hat blocks;
![85036ff1-b272-4d9a-8c53-a81cb04f4282](https://user-images.githubusercontent.com/13686399/27408574-378abd68-5692-11e7-96e7-451911999b81.gif)
![c1462111-18c2-4878-bd9e-f6a97677bfde](https://user-images.githubusercontent.com/13686399/27408589-49d2ca9c-5692-11e7-82a0-2d7b327be67c.gif)

@carljbowman @thisandagain does that sound right?

**Comment by rschamp** [comment]
@rachel-fenichel That sounds right to me!

**Comment by towerofnix** [comment]
> Looks like this was accidentally closed by the merge/06-28 (the commit that "fixes" this was targeting an issue in google/blockly, not the issue with the same ID in LLK/scratch-blocks.)
