### ISSUE TITLE
Design List Block

### ISSUE THREAD

**Issue by marisaleung** [LLK/scratch-blocks#984]
A “List” is simply a variable model with type “list.” So most of the behavior is similar to the variable design here: https://github.com/LLK/scratch-blocks/issues/372.

- Clicking on the list block (it's a reporter) evaluates it and pops up the current value.
- Right clicking brings up a context menu that includes the names of all of the other lists, delete, and rename.
- A block with a list field (usually “add to”, “delete of”, etc) shows the name of the list and a dropdown arrow.
- Clicking on the dropdown arrow shows a dropdown with the names of all the other lists.
- Making a new list in Scratch is done with the "Make a List" button in the Data category.
- Renaming a list in Scratch can be done by right-clicking on a reporter in the toolbox, but not by right clicking on a reporter in the workspace or by right-clicking on a setter anywhere.
- Deletion will behave as variable deletion does. Variable deletion is being decided upon in https://github.com/LLK/scratch-blocks/issues/975

- Scratch 2.0 only lets you delete/rename variables from the context menu when right clicking the reporter. Do we want to allow them to also delete/rename variable in the dropdowns as well?

**Comment by towerofnix** [comment]
> Clicking on the list block (it's a reporter) evaluates it and pops up the current value.

A quick note on this, though technically it's more relevant to the VM (and may already be implemented)..

* Scratch reports lists as strings.

* **If a list contains any items with two or more characters, or any items with zero characters,** the items are separated by strings. E.g. [foo, bar, kaz] -> "foo bar kaz"

* **If a list only contains items with one character,** the items are joined together without any space separations. E.g. [a, b, c, 1, 2, 3] -> "abc123"

Just so that there's no confusion when implementing the block and looking at its results!

**Comment by ateesdalejr** [comment]
@liam4 You are correct on the single character concatenation quirk. They will need to keep this in order to stop a few cloud projects from breaking.

**Comment by towerofnix** [comment]
@ateesdalejr I've also used it many times for substring procedures:

![Scratchblocks](https://user-images.githubusercontent.com/9948030/28431785-e289f334-6d5b-11e7-80b1-72512543e6a7.png)

**Comment by jwzimmer-zz** [comment]
Looking at this with @ericrosenbaum, we're not seeing how to rename a list in Scratch 2.0. We also got a request from a Scratcher in a workshop (10/16/17) to be able to rename a list in Scratch 3.0, so we wanted to make a note of that request for consideration here.
